"use client";

import Link from "next/link";
import {useMemo,useRef,useState} from "react";
import {ArrowRight,BadgeCheck,BookOpenCheck,ChefHat,CircleDollarSign,Coffee,Flame,ForkKnife,GlassWater,Info,Leaf,MessageSquareText,Scale,Search,ShieldCheck,Soup,Sparkles,Utensils,Volume2,Wheat} from "lucide-react";
import type {LucideIcon} from "lucide-react";
import {speakFrench} from "@/lib/frenchSpeech";
import "./restaurant.css";

type Phrase={fr:string;ar:string};
type Situation={id:string;fr:string;ar:string;tag:string;image:string;phrases:Phrase[]};
type Dish={fr:string;ar:string;gender:string;note:string};
type MenuGroup={id:string;fr:string;ar:string;image:string;dishes:Dish[]};
type Tool={fr:string;ar:string;note:string;Icon:LucideIcon};
type DialogueLine={role:string;fr:string;ar:string};
type Dialogue={id:string;fr:string;ar:string;context:string;lines:DialogueLine[]};
const p=(fr:string,ar:string):Phrase=>({fr,ar});

const situations:Situation[]=[
 {id:"reservation",fr:"Réserver une table",ar:"حجز طاولة",tag:"Avant la visite",image:"hero",phrases:[p("Bonjour, je voudrais réserver une table pour ce soir.","مرحبًا، أود حجز طاولة لهذا المساء."),p("Pour combien de personnes souhaitez-vous réserver ?","لكم شخصًا ترغب في الحجز؟"),p("Nous serons quatre personnes à vingt heures.","سنكون أربعة أشخاص عند الساعة الثامنة مساءً."),p("Avez-vous une table près de la fenêtre ?","هل لديكم طاولة قرب النافذة؟"),p("Votre réservation est confirmée au nom de Fahd.","تم تأكيد حجزك باسم فهد.")]},
 {id:"accueil",fr:"Accueil et placement",ar:"الاستقبال والجلوس",tag:"À l’arrivée",image:"hero",phrases:[p("Bonsoir, nous avons une réservation au nom de Fahd.","مساء الخير، لدينا حجز باسم فهد."),p("Bienvenue. Permettez-moi de vérifier votre réservation.","أهلًا بك. اسمح لي بالتحقق من حجزك."),p("Votre table est prête, veuillez me suivre.","طاولتكم جاهزة، تفضلوا باتباعي."),p("Cette table vous convient-elle ?","هل تناسبكم هذه الطاولة؟"),p("Le serveur va vous apporter la carte.","سيحضر لكم النادل قائمة الطعام.")]},
 {id:"carte",fr:"Lire la carte",ar:"قراءة قائمة الطعام",tag:"Le menu",image:"starters",phrases:[p("Pourrais-je voir la carte, s’il vous plaît ?","هل يمكنني رؤية قائمة الطعام من فضلك؟"),p("Quel est le plat du jour ?","ما طبق اليوم؟"),p("Que me conseillez-vous comme entrée ?","بماذا تنصحني كمقبلات؟"),p("Ce plat est-il servi avec des légumes ?","هل يُقدَّم هذا الطبق مع الخضروات؟"),p("J’ai besoin de quelques minutes pour choisir.","أحتاج إلى بضع دقائق للاختيار.")]},
 {id:"commande",fr:"Passer la commande",ar:"طلب الطعام",tag:"Commander",image:"mains",phrases:[p("Nous sommes prêts à commander.","نحن مستعدون للطلب."),p("Je prendrai la soupe en entrée et le poisson en plat principal.","سآخذ الحساء كمقبلات والسمك كطبق رئيسي."),p("Quelle cuisson souhaitez-vous pour la viande ?","ما درجة الطهي التي تريدها للحوم؟"),p("Je voudrais la sauce à part, s’il vous plaît.","أريد الصلصة منفصلة من فضلك."),p("Pourriez-vous apporter du pain supplémentaire ?","هل يمكنكم إحضار مزيد من الخبز؟")]},
 {id:"entrees",fr:"Entrées",ar:"المقبلات",tag:"Premier service",image:"starters",phrases:[p("La soupe à l’oignon est servie très chaude.","يُقدَّم حساء البصل ساخنًا جدًا."),p("La salade est assaisonnée avec une vinaigrette légère.","السلطة متبلة بصلصة خفيفة."),p("Cette tarte aux légumes est faite maison.","فطيرة الخضروات هذه محضّرة في المطعم."),p("Je voudrais partager cette entrée.","أود مشاركة هذه المقبلات."),p("L’entrée sera servie dans quelques minutes.","ستُقدَّم المقبلات خلال بضع دقائق.")]},
 {id:"plats",fr:"Plats principaux",ar:"الأطباق الرئيسية",tag:"Plat principal",image:"mains",phrases:[p("Le poulet rôti est accompagné de légumes.","يُقدَّم الدجاج المشوي مع الخضروات."),p("Le poisson est grillé et servi avec du citron.","السمك مشوي ويُقدَّم مع الليمون."),p("Le bœuf mijoté est très tendre.","اللحم البقري المطهو ببطء طري جدًا."),p("La ratatouille est un plat à base de légumes.","الراتاتوي طبق يعتمد على الخضروات."),p("Pourriez-vous servir une portion plus petite ?","هل يمكنكم تقديم حصة أصغر؟")]},
 {id:"boissons",fr:"Boissons sans alcool",ar:"المشروبات غير الكحولية",tag:"Boissons",image:"tableware",phrases:[p("Je voudrais une bouteille d’eau plate.","أريد زجاجة مياه غير غازية."),p("Préférez-vous de l’eau plate ou gazeuse ?","هل تفضل مياهًا غير غازية أم غازية؟"),p("Avez-vous du jus d’orange frais ?","هل لديكم عصير برتقال طازج؟"),p("Je prendrai un thé sans sucre.","سآخذ شايًا من دون سكر."),p("Un café, s’il vous plaît.","قهوة من فضلك.")]},
 {id:"desserts",fr:"Desserts",ar:"الحلويات",tag:"Fin du repas",image:"desserts",phrases:[p("Que proposez-vous comme dessert ?","ماذا تقدمون من الحلويات؟"),p("Je voudrais une crème brûlée.","أريد كريم بروليه."),p("La mousse au chocolat est-elle faite maison ?","هل موس الشوكولاتة محضّر في المطعم؟"),p("Nous partagerons une tarte aux pommes.","سنتشارك فطيرة تفاح."),p("Je préfère une salade de fruits sans sucre ajouté.","أفضل سلطة فواكه من دون سكر مضاف.")]},
 {id:"allergies",fr:"Allergies et régimes",ar:"الحساسية والأنظمة الغذائية",tag:"À signaler",image:"nutrition",phrases:[p("Je suis allergique aux fruits à coque.","لدي حساسية من المكسرات."),p("Ce plat contient-il du gluten ?","هل يحتوي هذا الطبق على الغلوتين؟"),p("Je ne consomme pas de produits laitiers.","لا أتناول منتجات الألبان."),p("Pouvez-vous vérifier les ingrédients auprès du chef ?","هل يمكنك التحقق من المكونات لدى الطاهي؟"),p("Une contamination croisée est-elle possible ?","هل يمكن حدوث تلوث تبادلي؟")]},
 {id:"nutrition",fr:"Calories et nutrition",ar:"السعرات والمعلومات الغذائية",tag:"Valeurs nutritionnelles",image:"nutrition",phrases:[p("Combien de calories contient ce plat ?","كم سعرة حرارية يحتوي عليها هذا الطبق؟"),p("Les valeurs nutritionnelles sont-elles disponibles ?","هل القيم الغذائية متاحة؟"),p("Quel est le plat le moins calorique ?","ما الطبق الأقل في السعرات؟"),p("Je voudrais une portion plus légère.","أريد حصة أخف."),p("Puis-je remplacer les frites par des légumes ?","هل يمكنني استبدال البطاطس المقلية بالخضروات؟"),p("Quelle quantité de protéines ce repas apporte-t-il ?","ما كمية البروتين التي توفرها هذه الوجبة؟"),p("Cette sauce est-elle riche en matières grasses ?","هل هذه الصلصة غنية بالدهون؟"),p("Ce dessert contient-il beaucoup de sucre ?","هل تحتوي هذه الحلوى على الكثير من السكر؟"),p("La valeur calorique dépend de la recette et de la portion.","تعتمد قيمة السعرات على الوصفة وحجم الحصة."),p("Je surveille mon apport calorique quotidien.","أراقب كمية السعرات التي أتناولها يوميًا.")]},
 {id:"probleme",fr:"Signaler un problème",ar:"الإبلاغ عن مشكلة",tag:"Service",image:"hero",phrases:[p("Excusez-moi, ce plat n’est pas celui que j’ai commandé.","عذرًا، هذا ليس الطبق الذي طلبته."),p("Mon plat est froid.","طبقي بارد."),p("Il manque un accompagnement.","هناك طبق جانبي ناقص."),p("Je suis désolé, nous allons remplacer le plat immédiatement.","أعتذر، سنستبدل الطبق فورًا."),p("Merci d’avoir signalé ce problème.","شكرًا لإبلاغنا بهذه المشكلة.")]},
 {id:"addition",fr:"Demander l’addition",ar:"طلب الفاتورة",tag:"Fin du service",image:"tableware",phrases:[p("L’addition, s’il vous plaît.","الفاتورة من فضلك."),p("Pouvons-nous payer séparément ?","هل يمكننا الدفع بشكل منفصل؟"),p("Je vais régler par carte bancaire.","سأدفع بالبطاقة المصرفية."),p("Pourriez-vous vérifier l’addition ?","هل يمكنك التحقق من الفاتورة؟"),p("Merci, le repas était excellent.","شكرًا، كانت الوجبة ممتازة.")]}
];

const menuGroups:MenuGroup[]=[
 {id:"starters",fr:"Les entrées",ar:"المقبلات",image:"starters",dishes:[{fr:"La soupe à l’oignon",ar:"حساء البصل",gender:"Féminin · Une",note:"حساء ساخن بالبصل"},{fr:"La salade verte",ar:"السلطة الخضراء",gender:"Féminin · Une",note:"خضروات ورقية مع تتبيلة"},{fr:"La tarte aux légumes",ar:"فطيرة الخضروات",gender:"Féminin · Une",note:"فطيرة مخبوزة بالخضروات"},{fr:"Le saumon fumé",ar:"السلمون المدخن",gender:"Masculin · Un",note:"شرائح سلمون مدخن"}]},
 {id:"mains",fr:"Les plats principaux",ar:"الأطباق الرئيسية",image:"mains",dishes:[{fr:"Le poulet rôti",ar:"الدجاج المشوي",gender:"Masculin · Un",note:"دجاج مشوي مع الأعشاب"},{fr:"Le poisson grillé",ar:"السمك المشوي",gender:"Masculin · Un",note:"شرائح سمك مشوية"},{fr:"Le bœuf mijoté",ar:"لحم بقري مطهو ببطء",gender:"Masculin · Un",note:"لحم مع خضروات"},{fr:"La ratatouille",ar:"راتاتوي الخضروات",gender:"Féminin · Une",note:"طبق خضروات مطهوة"}]},
 {id:"desserts",fr:"Les desserts",ar:"الحلويات",image:"desserts",dishes:[{fr:"La crème brûlée",ar:"كريم بروليه",gender:"Féminin · Une",note:"كريمة بسطح سكري مكرمل"},{fr:"La mousse au chocolat",ar:"موس الشوكولاتة",gender:"Féminin · Une",note:"حلوى شوكولاتة خفيفة"},{fr:"La tarte aux pommes",ar:"فطيرة التفاح",gender:"Féminin · Une",note:"فطيرة بشرائح التفاح"},{fr:"La salade de fruits",ar:"سلطة الفواكه",gender:"Féminin · Une",note:"فواكه طازجة متنوعة"}]},
 {id:"drinks",fr:"Les boissons",ar:"المشروبات",image:"tableware",dishes:[{fr:"L’eau plate",ar:"مياه غير غازية",gender:"Féminin · Une",note:"مياه للشرب"},{fr:"L’eau gazeuse",ar:"مياه غازية",gender:"Féminin · Une",note:"مياه تحتوي على فقاعات"},{fr:"Le jus d’orange",ar:"عصير البرتقال",gender:"Masculin · Un",note:"عصير فواكه"},{fr:"Le café",ar:"القهوة",gender:"Masculin · Un",note:"مشروب ساخن"},{fr:"Le thé",ar:"الشاي",gender:"Masculin · Un",note:"منقوع أوراق الشاي"}]}
];

const tools:Tool[]=[{fr:"L’assiette",ar:"الطبق",note:"لتقديم الطعام",Icon:Utensils},{fr:"La fourchette",ar:"الشوكة",note:"لالتقاط الطعام",Icon:ForkKnife},{fr:"Le couteau",ar:"السكين",note:"لتقطيع الطعام",Icon:ForkKnife},{fr:"La cuillère",ar:"الملعقة",note:"للحساء والأطعمة اللينة",Icon:Soup},{fr:"Le verre d’eau",ar:"كأس الماء",note:"لتقديم الماء",Icon:GlassWater},{fr:"La tasse",ar:"الفنجان",note:"للمشروبات الساخنة",Icon:Coffee},{fr:"Le plateau",ar:"الصينية",note:"لنقل الأطباق",Icon:Utensils},{fr:"La serviette de table",ar:"منديل المائدة",note:"يوضع بجانب الطبق",Icon:Sparkles},{fr:"La corbeille à pain",ar:"سلة الخبز",note:"لتقديم الخبز",Icon:Wheat},{fr:"La carte",ar:"قائمة الطعام",note:"لعرض الأطباق",Icon:BookOpenCheck},{fr:"L’addition",ar:"الفاتورة",note:"تفاصيل الطلب",Icon:CircleDollarSign},{fr:"La carafe d’eau",ar:"إبريق الماء",note:"لتقديم الماء",Icon:GlassWater}];

const dialogues:Dialogue[]=[
 {id:"book",fr:"Réserver une table",ar:"حجز طاولة",context:"مكالمة حجز قبل زيارة المطعم",lines:[{role:"Client",fr:"Bonjour, je voudrais réserver une table pour samedi soir.",ar:"مرحبًا، أود حجز طاولة مساء السبت."},{role:"Restaurant",fr:"Avec plaisir. Pour combien de personnes ?",ar:"بكل سرور. لكم شخصًا؟"},{role:"Client",fr:"Pour quatre personnes, vers vingt heures.",ar:"لأربعة أشخاص، نحو الساعة الثامنة."},{role:"Restaurant",fr:"Nous avons une table disponible à vingt heures quinze.",ar:"لدينا طاولة متاحة الساعة الثامنة والربع."},{role:"Client",fr:"Cela nous convient. Une personne utilise un fauteuil roulant.",ar:"هذا يناسبنا. أحد الأشخاص يستخدم كرسيًا متحركًا."},{role:"Restaurant",fr:"Je vais vous réserver une table facilement accessible.",ar:"سأحجز لكم طاولة يسهل الوصول إليها."},{role:"Client",fr:"Merci. La réservation est au nom de Salem.",ar:"شكرًا. الحجز باسم سالم."},{role:"Restaurant",fr:"C’est noté. À samedi, monsieur Salem.",ar:"تم تسجيله. نراكم السبت يا سيد سالم."}]},
 {id:"order",fr:"Commander le repas",ar:"طلب الوجبة",context:"حوار كامل بين النزيل والنادل",lines:[{role:"Serveur",fr:"Bonsoir, avez-vous choisi ?",ar:"مساء الخير، هل اخترتم؟"},{role:"Client",fr:"Oui. Je voudrais la soupe à l’oignon en entrée.",ar:"نعم. أريد حساء البصل كمقبلات."},{role:"Serveur",fr:"Et comme plat principal ?",ar:"وماذا تريد كطبق رئيسي؟"},{role:"Client",fr:"Le poisson grillé avec des légumes, s’il vous plaît.",ar:"السمك المشوي مع الخضروات من فضلك."},{role:"Serveur",fr:"Souhaitez-vous la sauce à part ?",ar:"هل ترغب في الصلصة منفصلة؟"},{role:"Client",fr:"Oui, et sans beurre si possible.",ar:"نعم، ومن دون زبدة إن أمكن."},{role:"Serveur",fr:"Très bien. Que désirez-vous boire ?",ar:"حسنًا. ماذا ترغب أن تشرب؟"},{role:"Client",fr:"Une carafe d’eau et un jus d’orange.",ar:"إبريق ماء وعصير برتقال."}]},
 {id:"allergy",fr:"Expliquer une allergie",ar:"توضيح حساسية",context:"التحقق من المكونات قبل الطلب",lines:[{role:"Client",fr:"Avant de commander, je dois vous signaler une allergie.",ar:"قبل الطلب، يجب أن أخبرك بوجود حساسية."},{role:"Serveur",fr:"Bien sûr. À quel aliment êtes-vous allergique ?",ar:"بالتأكيد. ما الطعام الذي لديك حساسية منه؟"},{role:"Client",fr:"Je suis allergique aux fruits à coque.",ar:"لدي حساسية من المكسرات."},{role:"Serveur",fr:"Je vais vérifier la recette et le risque de contamination croisée.",ar:"سأتحقق من الوصفة وخطر التلوث التبادلي."},{role:"Client",fr:"Merci. La salade contient-elle des noix ?",ar:"شكرًا. هل تحتوي السلطة على الجوز؟"},{role:"Serveur",fr:"La recette habituelle en contient, mais le chef peut l’adapter.",ar:"الوصفة المعتادة تحتوي عليه، لكن يمكن للطاهي تعديلها."},{role:"Client",fr:"Je préfère choisir un plat préparé séparément.",ar:"أفضل اختيار طبق يُحضّر بشكل منفصل."},{role:"Serveur",fr:"Je vais vous indiquer les options les plus sûres.",ar:"سأوضح لك الخيارات الأكثر أمانًا."}]},
 {id:"bill",fr:"Demander l’addition",ar:"طلب الفاتورة",context:"إنهاء الوجبة والدفع",lines:[{role:"Client",fr:"Excusez-moi, pourrions-nous avoir l’addition ?",ar:"عذرًا، هل يمكننا الحصول على الفاتورة؟"},{role:"Serveur",fr:"Bien sûr. Souhaitez-vous une seule addition ?",ar:"بالتأكيد. هل تريدون فاتورة واحدة؟"},{role:"Client",fr:"Nous aimerions payer séparément.",ar:"نرغب في الدفع بشكل منفصل."},{role:"Serveur",fr:"D’accord. Je vais séparer les commandes.",ar:"حسنًا. سأفصل الطلبات."},{role:"Client",fr:"Je règle mon repas par carte bancaire.",ar:"سأدفع ثمن وجبتي بالبطاقة المصرفية."},{role:"Serveur",fr:"Vous pouvez insérer votre carte dans le terminal.",ar:"يمكنك إدخال بطاقتك في جهاز الدفع."},{role:"Client",fr:"Merci, le service était excellent.",ar:"شكرًا، كانت الخدمة ممتازة."},{role:"Serveur",fr:"Merci à vous. Nous espérons vous revoir bientôt.",ar:"شكرًا لكم. نأمل رؤيتكم قريبًا."}]}
];

const navItems=[{id:"situations",fr:"Situations",ar:"المواقف",Icon:ChefHat},{id:"menu",fr:"La carte",ar:"الأطباق",Icon:BookOpenCheck},{id:"nutrition",fr:"Nutrition",ar:"السعرات",Icon:Flame},{id:"tools",fr:"Les outils",ar:"أدوات المائدة",Icon:ForkKnife},{id:"dialogues",fr:"Dialogues",ar:"المحادثات",Icon:MessageSquareText}] as const;

export default function RestaurantPage(){
 const [view,setView]=useState<(typeof navItems)[number]["id"]>("situations");
 const [activeSituation,setActiveSituation]=useState("reservation");
 const [activeMenu,setActiveMenu]=useState("starters");
 const [activeDialogue,setActiveDialogue]=useState("book");
 const [query,setQuery]=useState("");
 const detailRef=useRef<HTMLElement>(null);
 const currentSituation=situations.find(item=>item.id===activeSituation)??situations[0];
 const currentMenu=menuGroups.find(item=>item.id===activeMenu)??menuGroups[0];
 const currentDialogue=dialogues.find(item=>item.id===activeDialogue)??dialogues[0];
 const nutrition=situations.find(item=>item.id==="nutrition")!;
 const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase("fr");return q?situations.filter(item=>`${item.fr} ${item.ar} ${item.tag}`.toLocaleLowerCase("fr").includes(q)):situations},[query]);
 const speak=(text:string)=>void speakFrench(text,{rate:.76});
 const selectAndScroll=(setter:(id:string)=>void,id:string)=>{setter(id);window.setTimeout(()=>detailRef.current?.scrollIntoView({behavior:"smooth",block:"start"}),0)};

 return <main className="restaurant-world" dir="rtl">
  <header className="restaurant-topbar"><Link href="/kingdom" aria-label="العودة إلى واجهة القلعة"><ArrowRight/></Link><div><ChefHat/><span><strong>LE RESTAURANT</strong><small>المطعم التعليمي</small></span></div><div className="restaurant-service"><i/> Service en cours</div></header>
  <section className="restaurant-hero"><img src="/restaurant-v1/hero.webp" alt="مطعم فرنسي واقعي وفخم"/><div className="restaurant-hero-shade"/><div className="restaurant-hero-copy"><span><BadgeCheck/> Français pratique au restaurant</span><h1>À table !<br/><em>Bon appétit</em></h1><p>تعلّم الحجز والطلب والمكونات والسعرات والمحادثة داخل تجربة مطعم فرنسي متكاملة.</p><button onClick={()=>document.querySelector(".restaurant-main-nav")?.scrollIntoView({behavior:"smooth"})}>ابدأ التجربة <ArrowRight/></button></div><div className="restaurant-hero-stats"><div><b>{situations.length}</b><span>موقفًا عمليًا</span></div><div><b>{situations.reduce((n,item)=>n+item.phrases.length,0)}</b><span>جملة فرنسية</span></div><div><b>{menuGroups.reduce((n,item)=>n+item.dishes.length,0)}</b><span>طبقًا ومشروبًا</span></div></div></section>
  <nav className="restaurant-main-nav" aria-label="أقسام تعلم المطعم">{navItems.map(({id,fr,ar,Icon})=><button key={id} aria-label={`${fr} — ${ar}`} className={view===id?"active":""} onClick={()=>setView(id)}><Icon/><span><strong>{fr}</strong><small>{ar}</small></span></button>)}</nav>

  {view==="situations"&&<section className="restaurant-section"><div className="restaurant-title"><span>01 · Parcours du client</span><h2>مواقف المطعم من الحجز إلى المغادرة</h2><p>اختر الموقف للانتقال تلقائيًا إلى جمله، ثم اضغط على الجملة لسماعها.</p></div><label className="restaurant-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن موقف… Rechercher une situation"/></label><div className="restaurant-situation-grid">{filtered.map((item,index)=><button key={item.id} className={activeSituation===item.id?"active":""} onClick={()=>selectAndScroll(setActiveSituation,item.id)} style={{backgroundImage:`linear-gradient(180deg,transparent 15%,#29100fec 100%),url(/restaurant-v1/${item.image}.webp)`}}><i>{String(index+1).padStart(2,"0")}</i><span><small>{item.tag}</small><strong dir="ltr">{item.fr}</strong><b>{item.ar}</b></span><ArrowRight/></button>)}</div><article ref={detailRef} className="restaurant-detail"><header><img src={`/restaurant-v1/${currentSituation.image}.webp`} alt={currentSituation.ar}/><div><span>{currentSituation.tag}</span><h3 dir="ltr">{currentSituation.fr}</h3><p>{currentSituation.ar}</p></div></header><div className="restaurant-phrases">{currentSituation.phrases.map((item,index)=><button key={item.fr} onClick={()=>speak(item.fr)}><i>{String(index+1).padStart(2,"0")}</i><span><strong dir="ltr">{item.fr}</strong><small>{item.ar}</small></span><Volume2/></button>)}</div></article></section>}

  {view==="menu"&&<section className="restaurant-section"><div className="restaurant-title"><span>02 · La carte pédagogique</span><h2>قائمة تعليمية بلا أسعار</h2><p>صور ثابتة مطابقة للأطباق، مع النوع اللغوي والشرح والنطق المستقل.</p></div><div className="restaurant-menu-tabs">{menuGroups.map(item=><button key={item.id} className={activeMenu===item.id?"active":""} onClick={()=>selectAndScroll(setActiveMenu,item.id)}><strong dir="ltr">{item.fr}</strong><small>{item.ar}</small></button>)}</div><article ref={detailRef} className="restaurant-menu-card"><header><img src={`/restaurant-v1/${currentMenu.image}.webp`} alt={currentMenu.ar}/><div><span>CARTE PÉDAGOGIQUE</span><h3 dir="ltr">{currentMenu.fr}</h3><p>{currentMenu.ar}</p></div></header><div className="restaurant-dishes">{currentMenu.dishes.map((dish,index)=><button key={dish.fr} onClick={()=>speak(dish.fr)}><i>{String(index+1).padStart(2,"0")}</i><span><strong dir="ltr">{dish.fr}</strong><b>{dish.ar}</b><small dir="ltr">{dish.gender}</small><em>{dish.note}</em></span><Volume2/></button>)}</div></article></section>}

  {view==="nutrition"&&<section className="restaurant-section"><div className="restaurant-title"><span>03 · Calories et valeurs nutritionnelles</span><h2>السعرات والمعلومات الغذائية</h2><p>تعلّم السؤال عن الطاقة والحصة والمكونات دون تحويل القسم إلى نصيحة طبية.</p></div><article ref={detailRef} className="restaurant-nutrition"><header><img src="/restaurant-v1/nutrition.webp" alt="وجبة متوازنة ومكونات غذائية"/><div><Flame/><span><small>RÉFÉRENCE CIQUAL</small><h3>Calories et nutrition</h3><p>القيم تختلف باختلاف الوصفة ووزن الحصة؛ لذلك لا نعرض رقمًا ثابتًا بلا بيانات موثوقة.</p></span></div></header><div className="restaurant-nutrition-note"><Info/><p>عند إضافة قيم رقمية مستقبلًا ستُربط بقاعدة <b>Ciqual</b> التابعة لـ ANSES مع ذكر مقدار الحصة.</p></div><div className="restaurant-phrases">{nutrition.phrases.map((item,index)=><button key={item.fr} onClick={()=>speak(item.fr)}><i>{String(index+1).padStart(2,"0")}</i><span><strong dir="ltr">{item.fr}</strong><small>{item.ar}</small></span><Volume2/></button>)}</div><div className="restaurant-nutrients"><div><Flame/><span><strong>L’énergie</strong><small>الطاقة · kcal / kJ</small></span></div><div><Scale/><span><strong>La portion</strong><small>الحصة الغذائية</small></span></div><div><Leaf/><span><strong>Les fibres</strong><small>الألياف</small></span></div><div><Wheat/><span><strong>Les glucides</strong><small>الكربوهيدرات</small></span></div></div></article></section>}

  {view==="tools"&&<section className="restaurant-section"><div className="restaurant-title"><span>04 · Arts de la table</span><h2>أدوات المائدة والخدمة</h2><p>اضغط على الأداة لسماع اسمها بالفرنسية ومعرفة استعمالها.</p></div><article className="restaurant-tools"><header><img src="/restaurant-v1/tableware.webp" alt="أدوات مائدة مرتبة بصورة صحيحة"/><div><span>VOCABULAIRE</span><h3>Les arts de la table</h3><p>أدوات المائدة</p></div></header><div>{tools.map(({fr,ar,note,Icon},index)=><button key={fr} onClick={()=>speak(fr)}><i>{String(index+1).padStart(2,"0")}</i><Icon/><span><strong dir="ltr">{fr}</strong><b>{ar}</b><small>{note}</small></span><Volume2/></button>)}</div></article></section>}

  {view==="dialogues"&&<section className="restaurant-section"><div className="restaurant-title"><span>05 · Conversations complètes</span><h2>محادثات المطعم الكاملة</h2><p>أربع محادثات مختلفة؛ لكل سطر نطق مستقل وترجمة واضحة.</p></div><div className="restaurant-dialogue-tabs">{dialogues.map(item=><button key={item.id} className={activeDialogue===item.id?"active":""} onClick={()=>selectAndScroll(setActiveDialogue,item.id)}><MessageSquareText/><span><strong dir="ltr">{item.fr}</strong><small>{item.ar}</small></span></button>)}</div><article ref={detailRef} className="restaurant-dialogue"><header><span>CONVERSATION</span><h3 dir="ltr">{currentDialogue.fr}</h3><p>{currentDialogue.context}</p></header><div>{currentDialogue.lines.map((line,index)=><button key={`${line.fr}-${index}`} className={line.role==="Client"?"client":"staff"} onClick={()=>speak(line.fr)}><i>{line.role}</i><span><strong dir="ltr">{line.fr}</strong><small>{line.ar}</small></span><Volume2/></button>)}</div></article></section>}

  <section className="restaurant-sources"><div><ShieldCheck/><span><strong>مصطلحات ومعلومات موثوقة</strong><small>Sources françaises consultées</small></span></div><p>القيم الغذائية الرقمية لا تُفترض؛ وتُراجع عبر قاعدة Ciqual عند إضافتها إلى طبق محدد.</p><div><a href="https://ciqual.anses.fr/" target="_blank" rel="noreferrer">ANSES · Ciqual</a><a href="https://www.anses.fr/fr/content/allergies-alimentaires-et-etiquetage-de-precaution" target="_blank" rel="noreferrer">ANSES · Allergies alimentaires</a><a href="https://www.larousse.fr/dictionnaires/francais" target="_blank" rel="noreferrer">Larousse · Dictionnaire</a></div></section>
 </main>;
}
