"use client";

import Link from "next/link";
import {useRef,useState} from "react";
import type {CSSProperties} from "react";
import type {LucideIcon} from "lucide-react";
import {Activity,ArrowRight,BadgeCheck,BookOpen,Camera,CircleDot,ClipboardList,Flag,Play,Radio,ShieldCheck,Shirt,Trophy,Users,Video,Volume2,MessageSquareText} from "lucide-react";
import {speakFrench} from "@/lib/frenchSpeech";
import "./stadium.css";

type Phrase={fr:string;ar:string};
type Zone={id:string;fr:string;ar:string;tag:string;image:string;phrases:Phrase[]};
type Position={id:string;fr:string;ar:string;short:string;noteFr:string;noteAr:string;x:number;y:number};
type Rule={law:string;fr:string;ar:string;noteFr:string;noteAr:string};
type Equipment={fr:string;ar:string;note:string;Icon:LucideIcon};
type MediaTopic={id:string;fr:string;ar:string;tag:string;image:string;phrases:Phrase[]};
type Dialogue={id:string;fr:string;ar:string;context:string;lines:{role:string;fr:string;ar:string}[]};
const p=(fr:string,ar:string):Phrase=>({fr,ar});

const zones:Zone[]=[
 {id:"entree",fr:"Arrivée et contrôle d’accès",ar:"الوصول وبوابات الدخول",tag:"Avant le match",image:"hero",phrases:[p("Bonjour, dans quelle tribune se trouve mon siège ?","مرحبًا، في أي مدرج يقع مقعدي؟"),p("Veuillez présenter votre billet au contrôle.","يرجى إبراز تذكرتك عند التفتيش."),p("Votre entrée se trouve porte C.","مدخلك عند البوابة C."),p("Les objets interdits doivent rester à l’extérieur du stade.","يجب ترك الأشياء الممنوعة خارج الملعب."),p("Suivez la signalisation jusqu’à votre bloc.","اتبع اللوحات الإرشادية حتى تصل إلى قطاعك.")]},
 {id:"tribunes",fr:"Tribunes et placement",ar:"المدرجات والجلوس",tag:"Spectateurs",image:"hero",phrases:[p("Ma place se trouve au premier rang.","يقع مقعدي في الصف الأول."),p("Ce siège est-il libre ?","هل هذا المقعد شاغر؟"),p("La vue sur le terrain est excellente.","الرؤية على أرضية الملعب ممتازة."),p("L’escalier mène à la tribune supérieure.","يؤدي الدرج إلى المدرج العلوي."),p("Veuillez laisser le passage dégagé.","يرجى إبقاء الممر خاليًا.")]},
 {id:"terrain",fr:"Terrain et lignes de jeu",ar:"أرضية الملعب وخطوط اللعب",tag:"Aire de jeu",image:"match",phrases:[p("Les joueurs entrent sur le terrain.","يدخل اللاعبون إلى أرضية الملعب."),p("La ligne médiane partage le terrain en deux moitiés.","يقسم خط المنتصف الملعب إلى نصفين."),p("Le gardien se place dans sa surface de réparation.","يقف الحارس داخل منطقة الجزاء."),p("Le ballon est sorti en touche.","خرجت الكرة إلى رمية تماس."),p("L’arbitre indique un corner.","يشير الحكم إلى ركلة ركنية.")]},
 {id:"vestiaire",fr:"Vestiaire des joueurs",ar:"غرفة تبديل الملابس",tag:"Préparation",image:"locker",phrases:[p("Les joueurs se préparent dans le vestiaire.","يستعد اللاعبون في غرفة الملابس."),p("L’entraîneur présente le plan de jeu.","يعرض المدرب خطة اللعب."),p("Chaque joueur vérifie son équipement.","يتحقق كل لاعب من معداته."),p("Le capitaine encourage ses coéquipiers.","يشجع القائد زملاءه."),p("L’équipe rejoint le tunnel avant le coup d’envoi.","يتجه الفريق إلى الممر قبل صافرة البداية.")]},
 {id:"echauffement",fr:"Entraînement et échauffement",ar:"التدريب والإحماء",tag:"Avant-match",image:"locker",phrases:[p("L’équipe commence son échauffement.","يبدأ الفريق الإحماء."),p("Les joueurs effectuent des exercices de passes.","يؤدي اللاعبون تمارين التمرير."),p("Le préparateur physique installe les plots.","يضع معد اللياقة الأقماع التدريبية."),p("Le gardien travaille ses réflexes.","يدرب الحارس ردود أفعاله."),p("L’entraîneur demande plus d’intensité.","يطلب المدرب شدة أكبر.")]},
 {id:"match",fr:"Déroulement du match",ar:"مجريات المباراة",tag:"En jeu",image:"match",phrases:[p("L’arbitre donne le coup d’envoi.","يطلق الحكم صافرة البداية."),p("Le milieu de terrain récupère le ballon.","يستعيد لاعب الوسط الكرة."),p("L’attaquant fait une passe à son ailier.","يمرر المهاجم الكرة إلى الجناح."),p("La défense repousse l’attaque.","يبعد الدفاع الهجمة."),p("Le gardien réalise un bel arrêt.","يتصدى الحارس للكرة ببراعة.")]},
 {id:"buts",fr:"Attaques et buts",ar:"الهجمات والأهداف",tag:"Action",image:"match",phrases:[p("L’attaquant frappe vers le but.","يسدد المهاجم نحو المرمى."),p("Le ballon touche le poteau.","تصطدم الكرة بالقائم."),p("Le joueur marque de la tête.","يسجل اللاعب برأسه."),p("Le but est validé par l’arbitre.","يحتسب الحكم الهدف."),p("L’équipe égalise dans les dernières minutes.","يعادل الفريق النتيجة في الدقائق الأخيرة.")]},
 {id:"arbitrage",fr:"Arbitrage et fautes",ar:"التحكيم والمخالفات",tag:"Décisions",image:"equipment",phrases:[p("L’arbitre siffle une faute.","يطلق الحكم صافرته معلنًا مخالفة."),p("Le joueur reçoit un carton jaune.","يتلقى اللاعب بطاقة صفراء."),p("L’arbitre assistant lève son drapeau.","يرفع الحكم المساعد رايته."),p("Le joueur était en position de hors-jeu.","كان اللاعب في موقف تسلل."),p("Un penalty est accordé après la faute.","تُحتسب ركلة جزاء بعد المخالفة.")]},
 {id:"secours",fr:"Secours et sécurité",ar:"الإسعافات والأمن",tag:"Protection",image:"locker",phrases:[p("Le soigneur entre sur le terrain.","يدخل المسعف إلى أرضية الملعب."),p("Le joueur ressent une douleur à la cheville.","يشعر اللاعب بألم في الكاحل."),p("L’équipe médicale évalue la blessure.","يقيّم الفريق الطبي الإصابة."),p("Les agents de sécurité surveillent les tribunes.","يراقب رجال الأمن المدرجات."),p("La sortie de secours doit rester accessible.","يجب أن يبقى مخرج الطوارئ متاحًا.")]},
 {id:"supporters",fr:"Supporters et annonces",ar:"الجمهور والإعلانات الداخلية",tag:"Ambiance",image:"hero",phrases:[p("Les supporters encouragent leur équipe.","يشجع الجمهور فريقه."),p("Le public applaudit les joueurs.","يصفق الجمهور للاعبين."),p("L’annonceur présente la composition des équipes.","يعلن مذيع الملعب تشكيل الفريقين."),p("Le tableau d’affichage indique le score.","تعرض الشاشة نتيجة المباراة."),p("Merci de respecter les consignes de sécurité.","شكرًا لالتزامكم بتعليمات السلامة.")]},
 {id:"presse",fr:"Presse et zone mixte",ar:"الصحافة والمنطقة المختلطة",tag:"Médias",image:"press",phrases:[p("Les journalistes attendent dans la zone mixte.","ينتظر الصحفيون في المنطقة المختلطة."),p("Le reporter prépare son interview d’après-match.","يجهز المراسل مقابلته بعد المباراة."),p("Le joueur répond aux questions de la presse.","يجيب اللاعب عن أسئلة الصحافة."),p("La conférence de presse commence dans dix minutes.","يبدأ المؤتمر الصحفي بعد عشر دقائق."),p("Le photographe se place sur la plateforme réservée.","يقف المصور على المنصة المخصصة.")]},
 {id:"diffusion",fr:"Chaîne de télévision et diffusion",ar:"القناة الناقلة والبث",tag:"En direct",image:"broadcast",phrases:[p("La chaîne diffuse le match en direct.","تنقل القناة المباراة على الهواء مباشرة."),p("Le cadreur suit l’action avec sa caméra.","يتابع المصور الحدث بكاميرته."),p("Le réalisateur choisit le meilleur angle.","يختار مخرج البث أفضل زاوية."),p("La régie prépare un ralenti.","تجهز غرفة التحكم إعادة بطيئة."),p("Le signal est envoyé au réseau de diffusion.","تُرسل الإشارة إلى شبكة البث.")]},
 {id:"studio",fr:"Studio d’analyse",ar:"الاستديو التحليلي",tag:"Analyse",image:"studio",phrases:[p("Le présentateur accueille les analystes.","يرحب المذيع بالمحللين."),p("L’analyste explique la formation tactique.","يشرح المحلل التشكيل التكتيكي."),p("L’équipe a dominé la possession du ballon.","سيطر الفريق على الاستحواذ على الكرة."),p("L’écran affiche les statistiques du match.","تعرض الشاشة إحصائيات المباراة."),p("Les analystes reviennent sur les actions décisives.","يراجع المحللون اللقطات الحاسمة.")]},
 {id:"sortie",fr:"Après le match",ar:"بعد نهاية المباراة",tag:"Fin de rencontre",image:"press",phrases:[p("L’arbitre siffle la fin du match.","يطلق الحكم صافرة نهاية المباراة."),p("Les joueurs saluent les supporters.","يحيي اللاعبون الجمهور."),p("L’entraîneur rejoint la salle de presse.","يتجه المدرب إلى قاعة الصحافة."),p("Les spectateurs quittent le stade calmement.","يغادر المشجعون الملعب بهدوء."),p("La prochaine rencontre aura lieu dimanche.","ستقام المباراة القادمة يوم الأحد.")]}
];

const positions:Position[]=[
 {id:"gk",fr:"Le gardien de but",ar:"حارس المرمى",short:"GB",noteFr:"Il protège le but et relance le jeu.",noteAr:"يحمي المرمى ويبدأ بناء اللعب.",x:50,y:91},
 {id:"cb",fr:"Le défenseur central",ar:"قلب الدفاع",short:"DC",noteFr:"Il défend l’axe et gagne les duels.",noteAr:"يدافع عن العمق ويكسب المواجهات.",x:50,y:73},
 {id:"fb",fr:"L’arrière latéral",ar:"الظهير",short:"AL",noteFr:"Il défend le côté et soutient l’attaque.",noteAr:"يدافع على الطرف ويساند الهجوم.",x:17,y:67},
 {id:"dm",fr:"Le milieu défensif",ar:"لاعب الوسط الدفاعي",short:"MD",noteFr:"Il protège la défense et récupère le ballon.",noteAr:"يحمي الدفاع ويستعيد الكرة.",x:50,y:56},
 {id:"cm",fr:"Le milieu central",ar:"لاعب الوسط",short:"MC",noteFr:"Il organise les passes au centre du terrain.",noteAr:"ينظم التمريرات في وسط الملعب.",x:67,y:46},
 {id:"am",fr:"Le milieu offensif",ar:"صانع الألعاب",short:"MO",noteFr:"Il crée des occasions près de la surface.",noteAr:"يصنع الفرص قرب منطقة الجزاء.",x:50,y:34},
 {id:"wing",fr:"L’ailier",ar:"الجناح",short:"AI",noteFr:"Il attaque sur le côté et centre le ballon.",noteAr:"يهاجم على الطرف ويرسل العرضيات.",x:16,y:26},
 {id:"st",fr:"L’avant-centre",ar:"رأس الحربة",short:"AC",noteFr:"Il se place près du but pour marquer.",noteAr:"يتمركز قرب المرمى للتسجيل.",x:50,y:13}
];

const rules:Rule[]=[
 {law:"Loi 1",fr:"Le terrain",ar:"ميدان اللعب",noteFr:"Les lignes délimitent l’aire de jeu et ses différentes zones.",noteAr:"تحدد الخطوط أرضية اللعب ومناطقها المختلفة."},{law:"Loi 2",fr:"Le ballon",ar:"الكرة",noteFr:"Le ballon doit respecter les caractéristiques prévues par les Lois du Jeu.",noteAr:"يجب أن تطابق الكرة المواصفات الواردة في قوانين اللعبة."},{law:"Loi 3",fr:"Les joueurs",ar:"اللاعبون",noteFr:"Un match oppose deux équipes et chacune désigne un capitaine.",noteAr:"تجمع المباراة فريقين ويعيّن كل فريق قائدًا."},{law:"Loi 4",fr:"L’équipement",ar:"معدات اللاعبين",noteFr:"L’équipement obligatoire vise notamment à protéger les joueurs.",noteAr:"تهدف المعدات الإلزامية خصوصًا إلى حماية اللاعبين."},{law:"Loi 5",fr:"L’arbitre",ar:"الحكم",noteFr:"L’arbitre veille à l’application des Lois du Jeu.",noteAr:"يتولى الحكم تطبيق قوانين اللعبة."},{law:"Loi 7",fr:"La durée du match",ar:"مدة المباراة",noteFr:"Le match comporte deux périodes, avec le temps additionnel décidé par l’arbitre.",noteAr:"تتكون المباراة من شوطين مع وقت بدل ضائع يحدده الحكم."},{law:"Loi 8",fr:"Le coup d’envoi",ar:"ركلة البداية",noteFr:"Le coup d’envoi permet de commencer ou de reprendre le jeu.",noteAr:"تبدأ أو تُستأنف المباراة بركلة البداية."},{law:"Loi 9",fr:"Ballon en jeu et hors du jeu",ar:"الكرة داخل وخارج اللعب",noteFr:"Le ballon est hors du jeu lorsqu’il franchit entièrement une ligne de délimitation.",noteAr:"تكون الكرة خارج اللعب عندما تتجاوز بالكامل أحد خطوط الحدود."},{law:"Loi 10",fr:"L’issue d’un match",ar:"تحديد نتيجة المباراة",noteFr:"Un but est marqué lorsque le ballon franchit entièrement la ligne de but selon les Lois.",noteAr:"يُسجل الهدف عندما تتجاوز الكرة خط المرمى بالكامل وفق القوانين."},{law:"Loi 11",fr:"Le hors-jeu",ar:"التسلل",noteFr:"Une position de hors-jeu ne constitue pas, à elle seule, une infraction.",noteAr:"لا يُعد مجرد وجود اللاعب في موقف تسلل مخالفة بحد ذاته."},{law:"Loi 12",fr:"Fautes et incorrections",ar:"الأخطاء وسوء السلوك",noteFr:"Certaines infractions entraînent un coup franc ou une sanction disciplinaire.",noteAr:"تؤدي بعض المخالفات إلى ركلة حرة أو عقوبة انضباطية."},{law:"Lois 13–17",fr:"Reprises du jeu",ar:"استئناف اللعب",noteFr:"Coups francs, penalty, touche, coup de pied de but et corner relancent le jeu.",noteAr:"تستأنف المباراة بالركلات الحرة والجزاء والتماس وركلة المرمى والركنية."}
];

const equipment:Equipment[]=[
 {fr:"Le ballon",ar:"الكرة",note:"أداة اللعب الأساسية",Icon:CircleDot},{fr:"Le but",ar:"المرمى",note:"القائمان والعارضة والشبكة",Icon:Trophy},{fr:"Les gants du gardien",ar:"قفازات الحارس",note:"لحماية اليدين وتحسين الإمساك",Icon:ShieldCheck},{fr:"Le sifflet",ar:"الصافرة",note:"يستخدمها الحكم لإدارة اللعب",Icon:Volume2},{fr:"Le drapeau de touche",ar:"راية الحكم المساعد",note:"للإشارة إلى القرارات",Icon:Flag},{fr:"Les protège-tibias",ar:"واقيات الساق",note:"لحماية قصبة الساق",Icon:ShieldCheck},{fr:"Les chaussures à crampons",ar:"حذاء كرة القدم",note:"للثبات على أرضية الملعب",Icon:Activity},{fr:"Le brassard de capitaine",ar:"شارة القائد",note:"تميز قائد الفريق",Icon:BadgeCheck},{fr:"Le maillot",ar:"قميص اللعب",note:"جزء من زي اللاعب",Icon:Shirt},{fr:"Les plots d’entraînement",ar:"أقماع التدريب",note:"لتحديد مسارات التمرين",Icon:CircleDot},{fr:"Le tableau tactique",ar:"اللوح التكتيكي",note:"لشرح الخطة والتحركات",Icon:ClipboardList},{fr:"La caméra de télévision",ar:"كاميرا البث",note:"لنقل المباراة للمشاهدين",Icon:Camera}
];

const mediaTopics:MediaTopic[]=[
 {id:"conference",fr:"Conférence de presse",ar:"المؤتمر الصحفي",tag:"Presse",image:"press",phrases:[p("La conférence de presse débute après la rencontre.","يبدأ المؤتمر الصحفي بعد المباراة."),p("Le journaliste demande une précision à l’entraîneur.","يطلب الصحفي توضيحًا من المدرب."),p("Merci de lever la main avant de poser une question.","يرجى رفع اليد قبل طرح السؤال."),p("L’entraîneur analyse la performance de son équipe.","يحلل المدرب أداء فريقه."),p("La dernière question sera posée au capitaine.","سيُطرح السؤال الأخير على القائد.")]},
 {id:"mixed",fr:"Zone mixte et interviews",ar:"المنطقة المختلطة والمقابلات",tag:"Après-match",image:"press",phrases:[p("La zone mixte relie les vestiaires à la sortie des joueurs.","تربط المنطقة المختلطة غرف الملابس بمخرج اللاعبين."),p("Le reporter attend le meilleur joueur du match.","ينتظر المراسل أفضل لاعب في المباراة."),p("Pouvez-vous résumer cette rencontre ?","هل يمكنك تلخيص هذه المباراة؟"),p("Nous avons gardé notre concentration jusqu’à la fin.","حافظنا على تركيزنا حتى النهاية."),p("Le joueur rejoint ensuite la salle de presse.","يتجه اللاعب بعد ذلك إلى قاعة الصحافة.")]},
 {id:"channel",fr:"Chaîne de télévision",ar:"القناة الناقلة",tag:"Diffusion",image:"broadcast",phrases:[p("Bienvenue dans notre retransmission en direct.","أهلًا بكم في نقلنا المباشر."),p("La prise d’antenne aura lieu cinq minutes avant le match.","يبدأ البث قبل المباراة بخمس دقائق."),p("Le reporter intervient depuis le bord du terrain.","يتحدث المراسل من جانب الملعب."),p("La chaîne reçoit le signal international.","تستقبل القناة الإشارة الدولية."),p("La retransmission se termine après les interviews.","ينتهي النقل بعد المقابلات.")]},
 {id:"commentary",fr:"Commentaire en direct",ar:"التعليق المباشر",tag:"Micro",image:"broadcast",phrases:[p("Le commentateur décrit l’action en direct.","يصف المعلق الحدث مباشرة."),p("L’attaquant accélère sur le côté gauche.","يسرع المهاجم على الجهة اليسرى."),p("Quelle occasion exceptionnelle !","يا لها من فرصة استثنائية!"),p("Le gardien détourne le ballon en corner.","يبعد الحارس الكرة إلى ركلة ركنية."),p("L’arbitre ajoute quatre minutes.","يضيف الحكم أربع دقائق.")]},
 {id:"control",fr:"Régie et réalisation",ar:"غرفة التحكم والإخراج",tag:"Production",image:"broadcast",phrases:[p("La régie coordonne toutes les caméras.","تنسق غرفة التحكم جميع الكاميرات."),p("Préparez le ralenti de la dernière action.","جهزوا الإعادة البطيئة للهجمة الأخيرة."),p("La caméra principale suit le ballon.","تتبع الكاميرا الرئيسية الكرة."),p("Le réalisateur passe au plan large.","ينتقل المخرج إلى اللقطة الواسعة."),p("Vérifiez le son du commentateur.","تحققوا من صوت المعلق.")]},
 {id:"analysis",fr:"Plateau et analyse tactique",ar:"الاستديو والتحليل التكتيكي",tag:"Décryptage",image:"studio",phrases:[p("Observons la formation de départ.","لنلاحظ التشكيلة الأساسية."),p("Cette équipe défend dans un bloc compact.","يدافع هذا الفريق بكتلة متماسكة."),p("Le pressing a provoqué plusieurs pertes de balle.","تسبب الضغط في عدة حالات فقدان للكرة."),p("Le graphique compare les tirs des deux équipes.","يقارن الرسم تسديدات الفريقين."),p("Passons maintenant à l’analyse de la seconde période.","ننتقل الآن إلى تحليل الشوط الثاني.")]}
];

const dialogues:Dialogue[]=[
 {id:"gate",fr:"À l’entrée du stade",ar:"عند بوابة الملعب",context:"حوار بين المشجع وموظف التنظيم",lines:[{role:"Spectateur",fr:"Bonjour, est-ce la bonne entrée pour la tribune centrale ?",ar:"مرحبًا، هل هذا المدخل الصحيح للمدرج الأوسط؟"},{role:"Agent",fr:"Oui. Puis-je voir votre billet, s’il vous plaît ?",ar:"نعم. هل يمكنني رؤية تذكرتك من فضلك؟"},{role:"Spectateur",fr:"Bien sûr, le voici sur mon téléphone.",ar:"بالطبع، هذه هي على هاتفي."},{role:"Agent",fr:"Merci. Votre siège se trouve dans le bloc douze.",ar:"شكرًا. مقعدك في القطاع اثني عشر."},{role:"Spectateur",fr:"Comment puis-je y accéder ?",ar:"كيف يمكنني الوصول إليه؟"},{role:"Agent",fr:"Prenez l’escalier à droite, puis suivez les panneaux.",ar:"اصعد الدرج على اليمين ثم اتبع اللوحات."},{role:"Spectateur",fr:"Merci pour votre aide.",ar:"شكرًا لمساعدتك."},{role:"Agent",fr:"Je vous en prie. Bon match !",ar:"على الرحب والسعة. مباراة ممتعة!"}]},
 {id:"coach",fr:"Dans le vestiaire",ar:"داخل غرفة الملابس",context:"تعليمات المدرب قبل المباراة",lines:[{role:"Entraîneur",fr:"Messieurs, restez concentrés dès le coup d’envoi.",ar:"أيها اللاعبون، حافظوا على التركيز منذ البداية."},{role:"Capitaine",fr:"Nous devons jouer avec calme et discipline.",ar:"علينا أن نلعب بهدوء وانضباط."},{role:"Entraîneur",fr:"Le milieu doit conserver le ballon et changer rapidement de côté.",ar:"يجب على الوسط الاحتفاظ بالكرة وتغيير جهة اللعب بسرعة."},{role:"Joueur",fr:"Devons-nous presser leur défense ?",ar:"هل نضغط على دفاعهم؟"},{role:"Entraîneur",fr:"Oui, mais seulement lorsque le signal est donné.",ar:"نعم، ولكن فقط عند إعطاء الإشارة."},{role:"Capitaine",fr:"Nous communiquerons pendant toute la rencontre.",ar:"سنتواصل طوال المباراة."},{role:"Entraîneur",fr:"Parfait. Échauffez-vous encore cinq minutes.",ar:"ممتاز. واصلوا الإحماء خمس دقائق أخرى."},{role:"Joueurs",fr:"Nous sommes prêts, entraîneur.",ar:"نحن مستعدون يا مدرب."}]},
 {id:"press",fr:"Conférence de presse",ar:"المؤتمر الصحفي",context:"أسئلة الصحفيين بعد المباراة",lines:[{role:"Journaliste",fr:"Comment analysez-vous la performance de votre équipe ?",ar:"كيف تحلل أداء فريقك؟"},{role:"Entraîneur",fr:"Nous avons bien défendu, mais nous avons manqué de précision.",ar:"دافعنا جيدًا لكن افتقدنا الدقة."},{role:"Journaliste",fr:"Pourquoi avez-vous changé de formation en seconde période ?",ar:"لماذا غيرت التشكيل في الشوط الثاني؟"},{role:"Entraîneur",fr:"Je voulais renforcer le milieu de terrain.",ar:"أردت تعزيز خط الوسط."},{role:"Journaliste",fr:"Le résultat vous paraît-il juste ?",ar:"هل تبدو النتيجة عادلة لك؟"},{role:"Entraîneur",fr:"Les deux équipes ont eu des occasions.",ar:"حصل الفريقان على فرص."},{role:"Journaliste",fr:"Quel sera votre objectif pour le prochain match ?",ar:"ما هدفكم للمباراة القادمة؟"},{role:"Entraîneur",fr:"Nous allons récupérer, puis corriger nos erreurs.",ar:"سنستعيد عافيتنا ثم نصحح أخطاءنا."}]},
 {id:"broadcast",fr:"Dans la régie",ar:"داخل غرفة البث",context:"تنسيق القناة الناقلة أثناء المباراة",lines:[{role:"Réalisateur",fr:"Caméra un, gardez le plan large.",ar:"الكاميرا الأولى، حافظوا على اللقطة الواسعة."},{role:"Cadreur",fr:"La caméra est prête sur l’action.",ar:"الكاميرا جاهزة لمتابعة الهجمة."},{role:"Réalisateur",fr:"Préparez le ralenti derrière le but.",ar:"جهزوا الإعادة من خلف المرمى."},{role:"Technicien",fr:"Le ralenti est disponible.",ar:"الإعادة البطيئة جاهزة."},{role:"Réalisateur",fr:"Revenez au direct dans trois secondes.",ar:"عودوا إلى البث المباشر بعد ثلاث ثوانٍ."},{role:"Technicien",fr:"Le son du stade est bien équilibré.",ar:"صوت الملعب متوازن جيدًا."},{role:"Réalisateur",fr:"Informez le commentateur du changement.",ar:"أبلغوا المعلق بالتبديل."},{role:"Technicien",fr:"C’est fait, il a reçu l’information.",ar:"تم ذلك، وقد وصلته المعلومة."}]},
 {id:"commentator",fr:"Commentaire du match",ar:"التعليق على المباراة",context:"المعلق والمراسل الميداني",lines:[{role:"Commentateur",fr:"Le match reprend avec une attaque rapide.",ar:"تُستأنف المباراة بهجمة سريعة."},{role:"Reporter",fr:"Le nouvel attaquant se prépare à entrer.",ar:"يستعد المهاجم الجديد للدخول."},{role:"Commentateur",fr:"Le milieu trouve un espace entre les lignes.",ar:"يجد لاعب الوسط مساحة بين الخطوط."},{role:"Reporter",fr:"L’entraîneur demande à son équipe d’avancer.",ar:"يطلب المدرب من فريقه التقدم."},{role:"Commentateur",fr:"Quelle frappe, mais le gardien réalise un arrêt remarquable !",ar:"يا لها من تسديدة، لكن الحارس يتصدى ببراعة!"},{role:"Reporter",fr:"Le public se lève dans toute la tribune.",ar:"ينهض الجمهور في جميع المدرجات."},{role:"Commentateur",fr:"Il reste deux minutes dans le temps additionnel.",ar:"تبقت دقيقتان من الوقت بدل الضائع."},{role:"Reporter",fr:"La tension est maximale au bord du terrain.",ar:"التوتر في أعلى مستوياته بجانب الملعب."}]},
 {id:"studio",fr:"Analyse d’après-match",ar:"تحليل ما بعد المباراة",context:"نقاش المذيع والمحللين",lines:[{role:"Présentateur",fr:"Commençons par le tournant de cette rencontre.",ar:"لنبدأ بلحظة التحول في هذه المباراة."},{role:"Analyste",fr:"Le changement tactique a libéré les deux ailiers.",ar:"حرر التغيير التكتيكي الجناحين."},{role:"Présentateur",fr:"Les statistiques confirment-elles cette impression ?",ar:"هل تؤكد الإحصائيات هذا الانطباع؟"},{role:"Analyste",fr:"Oui, l’équipe a créé davantage d’occasions après la pause.",ar:"نعم، صنع الفريق فرصًا أكثر بعد الاستراحة."},{role:"Présentateur",fr:"Que pensez-vous du travail défensif ?",ar:"ما رأيك في العمل الدفاعي؟"},{role:"Analyste",fr:"La ligne défensive est restée compacte et bien organisée.",ar:"ظل خط الدفاع متماسكًا ومنظمًا جيدًا."},{role:"Présentateur",fr:"Regardons maintenant le but décisif.",ar:"لنشاهد الآن الهدف الحاسم."},{role:"Analyste",fr:"Le déplacement sans ballon crée tout l’espace nécessaire.",ar:"التحرك دون كرة يصنع المساحة اللازمة كاملة."}]}
];

const navItems=[{id:"tour",fr:"Le stade",ar:"جولة الملعب",Icon:Trophy},{id:"positions",fr:"Les postes",ar:"مراكز اللاعبين",Icon:Users},{id:"rules",fr:"Les règles",ar:"القواعد",Icon:BookOpen},{id:"equipment",fr:"L’équipement",ar:"الأدوات",Icon:Shirt},{id:"media",fr:"Les médias",ar:"الإعلام والبث",Icon:Radio},{id:"dialogues",fr:"Dialogues",ar:"المحادثات",Icon:MessageSquareText}] as const;

export default function StadiumPage(){
 const [view,setView]=useState<(typeof navItems)[number]["id"]>("tour");
 const [activeZone,setActiveZone]=useState("entree");
 const [activePosition,setActivePosition]=useState("gk");
 const [activeMedia,setActiveMedia]=useState("conference");
 const [activeDialogue,setActiveDialogue]=useState("gate");
 const detailRef=useRef<HTMLElement>(null);
 const currentZone=zones.find(item=>item.id===activeZone)??zones[0];
 const currentPosition=positions.find(item=>item.id===activePosition)??positions[0];
 const currentMedia=mediaTopics.find(item=>item.id===activeMedia)??mediaTopics[0];
 const currentDialogue=dialogues.find(item=>item.id===activeDialogue)??dialogues[0];
 const speak=(text:string)=>void speakFrench(text,{rate:.77});
 const selectAndScroll=(setter:(id:string)=>void,id:string)=>{setter(id);window.setTimeout(()=>detailRef.current?.scrollIntoView({behavior:"smooth",block:"start"}),0)};
 return <main className="stadium-world" dir="rtl">
  <header className="stadium-topbar"><Link href="/kingdom" aria-label="العودة إلى واجهة القلعة"><ArrowRight/></Link><div><Trophy/><span><strong>LE STADE</strong><small>ملعب تعلّم كرة القدم</small></span></div><div className="stadium-live"><i/> JOUR DE MATCH</div></header>
  <section className="stadium-hero"><img src="/stadium-v1/hero.webp" alt="ملعب كرة قدم واقعي من الداخل"/><div className="stadium-hero-shade"/><div className="stadium-hero-copy"><span><BadgeCheck/> FRANÇAIS DU FOOTBALL</span><h1>Entrez dans<br/><em>le grand stade</em></h1><p>من البوابة إلى أرضية الملعب، ومن غرفة اللاعبين إلى الصحافة والقناة الناقلة والاستديو التحليلي.</p><button onClick={()=>document.querySelector(".stadium-nav")?.scrollIntoView({behavior:"smooth"})}>ابدأ الجولة <Play/></button></div><div className="stadium-hero-stats"><div><b>{zones.length}</b><span>موقفًا داخل الملعب</span></div><div><b>{zones.reduce((n,item)=>n+item.phrases.length,0)}</b><span>جملة أساسية</span></div><div><b>{mediaTopics.length}</b><span>أقسام إعلامية</span></div></div></section>
  <nav className="stadium-nav" aria-label="أقسام تعلم كرة القدم">{navItems.map(({id,fr,ar,Icon})=><button key={id} aria-label={`${fr} — ${ar}`} className={view===id?"active":""} onClick={()=>setView(id)}><Icon/><span><strong dir="ltr">{fr}</strong><small>{ar}</small></span></button>)}</nav>

  {view==="tour"&&<section className="stadium-section"><div className="stadium-title"><span>01 · PARCOURS DU MATCH</span><h2>جولة الملعب من الدخول حتى نهاية المباراة</h2><p>اختر المكان وسينقلك النظام إلى جمله مباشرة؛ اضغط على أي جملة لسماع النطق الفرنسي.</p></div><div className="stadium-zone-grid">{zones.map((item,index)=><button key={item.id} className={activeZone===item.id?"active":""} onClick={()=>selectAndScroll(setActiveZone,item.id)} style={{backgroundImage:`linear-gradient(180deg,transparent 5%,#061b15f2 100%),url(/stadium-v1/${item.image}.webp)`}}><i>{String(index+1).padStart(2,"0")}</i><span><small>{item.tag}</small><strong dir="ltr">{item.fr}</strong><b>{item.ar}</b></span><ArrowRight/></button>)}</div><article ref={detailRef} className="stadium-detail"><header><img src={`/stadium-v1/${currentZone.image}.webp`} alt={currentZone.ar}/><div><span>{currentZone.tag}</span><h3 dir="ltr">{currentZone.fr}</h3><p>{currentZone.ar}</p></div></header><div className="stadium-phrases">{currentZone.phrases.map((item,index)=><button key={item.fr} onClick={()=>speak(item.fr)}><i>{String(index+1).padStart(2,"0")}</i><span><strong dir="ltr">{item.fr}</strong><small>{item.ar}</small></span><Volume2/></button>)}</div></article></section>}

  {view==="positions"&&<section className="stadium-section"><div className="stadium-title"><span>02 · COMPOSITION TACTIQUE</span><h2>مراكز اللاعبين على أرضية الملعب</h2><p>اضغط على المركز في الخطة لمعرفة اسمه ودوره وسماع نطقه.</p></div><div className="stadium-formation"><div className="stadium-pitch" dir="ltr">{positions.map(item=><button key={item.id} style={{"--x":`${item.x}%`,"--y":`${item.y}%`} as CSSProperties} className={activePosition===item.id?"active":""} onClick={()=>setActivePosition(item.id)}><b>{item.short}</b><span>{item.fr}</span></button>)}</div><article><span>POSTE SÉLECTIONNÉ</span><h3 dir="ltr">{currentPosition.fr}</h3><h4>{currentPosition.ar}</h4><p dir="ltr">{currentPosition.noteFr}</p><small>{currentPosition.noteAr}</small><button onClick={()=>speak(`${currentPosition.fr}. ${currentPosition.noteFr}`)}><Volume2/> استمع للنطق</button></article></div></section>}

  {view==="rules"&&<section className="stadium-section"><div className="stadium-title"><span>03 · LOIS DU JEU</span><h2>قواعد كرة القدم الأساسية</h2><p>ملخص تعليمي مبسط مستند إلى قوانين IFAB؛ اضغط على القاعدة لسماع شرحها الفرنسي.</p></div><div className="stadium-rule-grid">{rules.map((rule,index)=><button key={rule.law} onClick={()=>speak(`${rule.fr}. ${rule.noteFr}`)}><i>{String(index+1).padStart(2,"0")}</i><span>{rule.law}</span><BookOpen/><h3 dir="ltr">{rule.fr}</h3><h4>{rule.ar}</h4><p dir="ltr">{rule.noteFr}</p><small>{rule.noteAr}</small><Volume2/></button>)}</div><div className="stadium-rule-note"><ShieldCheck/><p>هذا القسم للتعلم اللغوي وفهم المصطلحات، والمرجع الكامل عند تطبيق القوانين هو الإصدار الحالي المنشور من IFAB.</p></div></section>}

  {view==="equipment"&&<section className="stadium-section"><div className="stadium-title"><span>04 · MATÉRIEL DU FOOTBALL</span><h2>أدوات ومعدات الملعب</h2><p>صورة ثابتة واقعية ومفردات مطابقة؛ اضغط على الأداة لسماع اسمها.</p></div><article className="stadium-equipment"><header><img src="/stadium-v1/equipment.webp" alt="معدات كرة قدم واقعية مرتبة على العشب"/><div><span>VOCABULAIRE VISUEL</span><h3>L’équipement</h3><p>معدات كرة القدم والتحكيم والبث</p></div></header><div>{equipment.map(({fr,ar,note,Icon},index)=><button key={fr} onClick={()=>speak(fr)}><i>{String(index+1).padStart(2,"0")}</i><Icon/><span><strong dir="ltr">{fr}</strong><b>{ar}</b><small>{note}</small></span><Volume2/></button>)}</div></article></section>}

  {view==="media"&&<section className="stadium-section"><div className="stadium-title"><span>05 · MÉDIAS ET DIFFUSION</span><h2>الصحافة والقناة الناقلة والاستديو التحليلي</h2><p>مسار إعلامي متكامل من المنطقة المختلطة إلى غرفة التحكم والتحليل بعد المباراة.</p></div><div className="stadium-media-grid">{mediaTopics.map(item=><button key={item.id} className={activeMedia===item.id?"active":""} onClick={()=>selectAndScroll(setActiveMedia,item.id)}><img src={`/stadium-v1/${item.image}.webp`} alt={item.ar}/><span><small>{item.tag}</small><strong dir="ltr">{item.fr}</strong><b>{item.ar}</b></span><Video/></button>)}</div><article ref={detailRef} className="stadium-detail stadium-media-detail"><header><img src={`/stadium-v1/${currentMedia.image}.webp`} alt={currentMedia.ar}/><div><span>{currentMedia.tag}</span><h3 dir="ltr">{currentMedia.fr}</h3><p>{currentMedia.ar}</p></div></header><div className="stadium-phrases">{currentMedia.phrases.map((item,index)=><button key={item.fr} onClick={()=>speak(item.fr)}><i>{String(index+1).padStart(2,"0")}</i><span><strong dir="ltr">{item.fr}</strong><small>{item.ar}</small></span><Volume2/></button>)}</div></article></section>}

  {view==="dialogues"&&<section className="stadium-section"><div className="stadium-title"><span>06 · CONVERSATIONS COMPLÈTES</span><h2>محادثات الملعب والإعلام الكاملة</h2><p>ست محادثات مختلفة، ولكل سطر نطق مستقل وترجمة واضحة.</p></div><div className="stadium-dialogue-tabs">{dialogues.map(item=><button key={item.id} className={activeDialogue===item.id?"active":""} onClick={()=>selectAndScroll(setActiveDialogue,item.id)}><MessageSquareText/><span><strong dir="ltr">{item.fr}</strong><small>{item.ar}</small></span></button>)}</div><article ref={detailRef} className="stadium-dialogue"><header><span>CONVERSATION</span><h3 dir="ltr">{currentDialogue.fr}</h3><p>{currentDialogue.context}</p></header><div>{currentDialogue.lines.map((line,index)=><button key={`${line.fr}-${index}`} className={index%2?"reply":"lead"} onClick={()=>speak(line.fr)}><i>{line.role}</i><span><strong dir="ltr">{line.fr}</strong><small>{line.ar}</small></span><Volume2/></button>)}</div></article></section>}

 </main>;
}
