"use client";

import Link from "next/link";
import {useMemo,useRef,useState} from "react";
import {ArrowRight,BadgeCheck,BedDouble,Bell,CircleDollarSign,ConciergeBell,CreditCard,KeyRound,Luggage,MessageSquareText,Phone,Search,ShieldCheck,Shirt,Sparkles,UtensilsCrossed,Volume2,WashingMachine,Wifi,Wind} from "lucide-react";
import type {LucideIcon} from "lucide-react";
import {speakFrench} from "@/lib/frenchSpeech";
import "./hotel.css";

type Phrase={fr:string;ar:string};
type Department={id:string;fr:string;ar:string;tag:string;image:string;phrases:Phrase[]};
type HotelObject={fr:string;ar:string;note:string;Icon:LucideIcon};
type ObjectRoom={id:string;fr:string;ar:string;image:string;objects:HotelObject[]};
type DialogueLine={role:string;fr:string;ar:string};
type Dialogue={id:string;fr:string;ar:string;context:string;lines:DialogueLine[]};
const p=(fr:string,ar:string):Phrase=>({fr,ar});

const departments:Department[]=[
 {id:"reservation",fr:"Réservation",ar:"الحجز",tag:"Avant le séjour",image:"concierge",phrases:[p("Bonjour, je voudrais réserver une chambre pour deux nuits.","مرحبًا، أود حجز غرفة لليلتين."),p("Avez-vous une chambre disponible du 12 au 14 juin ?","هل لديكم غرفة متاحة من 12 إلى 14 يونيو؟"),p("Je souhaite une chambre calme avec un grand lit.","أرغب في غرفة هادئة بسرير كبير."),p("Le petit-déjeuner est-il compris dans le tarif ?","هل الإفطار مشمول في السعر؟"),p("Pouvez-vous m’envoyer la confirmation par courriel ?","هل يمكنكم إرسال تأكيد الحجز عبر البريد الإلكتروني؟")]},
 {id:"arrivee",fr:"Arrivée et enregistrement",ar:"الوصول وتسجيل الدخول",tag:"Check-in",image:"hero",phrases:[p("Bonjour, j’ai une réservation au nom de Mansour.","مرحبًا، لدي حجز باسم منصور."),p("Puis-je voir votre pièce d’identité, s’il vous plaît ?","هل يمكنني رؤية هويتك من فضلك؟"),p("Votre chambre se trouve au quatrième étage.","تقع غرفتك في الطابق الرابع."),p("Voici votre carte de chambre.","هذه بطاقة غرفتك."),p("L’ascenseur est à gauche de la réception.","المصعد على يسار مكتب الاستقبال.")]},
 {id:"reception",fr:"Réception",ar:"الاستقبال",tag:"24 h / 24",image:"hero",phrases:[p("La réception est ouverte vingt-quatre heures sur vingt-quatre.","الاستقبال مفتوح على مدار الساعة."),p("Pourriez-vous m’indiquer le mot de passe du Wi-Fi ?","هل يمكن أن تخبرني بكلمة مرور شبكة الواي فاي؟"),p("J’aimerais recevoir un appel de réveil à six heures.","أود تلقي مكالمة إيقاظ الساعة السادسة."),p("Pouvez-vous appeler un taxi pour huit heures ?","هل يمكنكم طلب سيارة أجرة لي عند الساعة الثامنة؟"),p("Nous restons à votre disposition pendant tout le séjour.","نحن في خدمتك طوال مدة الإقامة.")]},
 {id:"chambre",fr:"Chambre et équipements",ar:"الغرفة وتجهيزاتها",tag:"Dans la chambre",image:"room",phrases:[p("La chambre est-elle équipée de la climatisation ?","هل الغرفة مجهزة بتكييف؟"),p("Le coffre-fort se trouve dans l’armoire.","توجد الخزنة داخل خزانة الملابس."),p("Pourriez-vous m’apporter un oreiller supplémentaire ?","هل يمكنكم إحضار وسادة إضافية؟"),p("La carte doit rester dans le lecteur pour activer l’électricité.","يجب أن تبقى البطاقة في القارئ لتشغيل الكهرباء."),p("Le téléphone permet de joindre directement la réception.","يتيح الهاتف الاتصال مباشرة بمكتب الاستقبال.")]},
 {id:"conciergerie",fr:"Conciergerie et bagages",ar:"خدمة النزلاء والأمتعة",tag:"Assistance",image:"concierge",phrases:[p("Puis-je laisser mes bagages à la consigne ?","هل يمكنني ترك أمتعتي في غرفة الحفظ؟"),p("Le bagagiste va monter vos valises dans la chambre.","سيصعد موظف الأمتعة بحقائبك إلى الغرفة."),p("Pourriez-vous me recommander un restaurant à proximité ?","هل يمكنك أن تنصحني بمطعم قريب؟"),p("Le concierge peut réserver vos billets de spectacle.","يمكن لموظف خدمة النزلاء حجز تذاكر العرض لك."),p("Vos bagages seront conservés jusqu’à votre départ.","ستُحفظ أمتعتك حتى موعد مغادرتك.")]},
 {id:"restauration",fr:"Restaurant et petit-déjeuner",ar:"المطعم والإفطار",tag:"Restauration",image:"restaurant",phrases:[p("À quelle heure le petit-déjeuner est-il servi ?","في أي ساعة يُقدَّم الإفطار؟"),p("Le petit-déjeuner est servi de sept heures à dix heures.","يُقدَّم الإفطار من السابعة حتى العاشرة."),p("Je voudrais une table près de la fenêtre.","أود طاولة قرب النافذة."),p("Avez-vous des plats sans gluten ?","هل لديكم أطباق خالية من الغلوتين؟"),p("Puis-je commander le petit-déjeuner dans ma chambre ?","هل يمكنني طلب الإفطار في غرفتي؟")]},
 {id:"entretien",fr:"Entretien et blanchisserie",ar:"التنظيف والغسيل",tag:"Service d’étage",image:"housekeeping",phrases:[p("Je souhaiterais faire nettoyer ma chambre.","أرغب في تنظيف غرفتي."),p("Pourriez-vous remplacer les serviettes, s’il vous plaît ?","هل يمكنكم استبدال المناشف من فضلكم؟"),p("Le service de blanchisserie est disponible du lundi au samedi.","خدمة الغسيل متاحة من الاثنين إلى السبت."),p("Veuillez remplir la fiche de blanchisserie.","يرجى تعبئة استمارة الغسيل."),p("Votre linge propre sera livré demain matin.","ستُسلَّم ملابسك النظيفة صباح الغد.")]},
 {id:"services",fr:"Services et installations",ar:"الخدمات والمرافق",tag:"Séjour",image:"room",phrases:[p("Le Wi-Fi est gratuit dans tout l’hôtel.","شبكة الواي فاي مجانية في جميع أنحاء الفندق."),p("La salle de sport se trouve au sous-sol.","تقع صالة الرياضة في الطابق السفلي."),p("La navette pour l’aéroport part toutes les heures.","تنطلق حافلة المطار كل ساعة."),p("La salle de réunion doit être réservée à l’avance.","يجب حجز قاعة الاجتماعات مسبقًا."),p("Un fer et une planche à repasser sont disponibles sur demande.","تتوفر مكواة وطاولة كي عند الطلب.")]},
 {id:"problemes",fr:"Demandes et problèmes",ar:"الطلبات والمشكلات",tag:"Assistance",image:"housekeeping",phrases:[p("La climatisation de ma chambre ne fonctionne pas.","تكييف غرفتي لا يعمل."),p("Il n’y a pas d’eau chaude dans la salle de bains.","لا توجد مياه ساخنة في الحمام."),p("La chambre voisine est très bruyante.","الغرفة المجاورة صاخبة جدًا."),p("Nous allons envoyer un technicien immédiatement.","سنرسل فنيًا فورًا."),p("Nous pouvons vous proposer une autre chambre.","يمكننا أن نقترح عليك غرفة أخرى.")]},
 {id:"depart",fr:"Facturation et départ",ar:"الفاتورة وتسجيل المغادرة",tag:"Check-out",image:"hero",phrases:[p("Je voudrais régler ma note et libérer la chambre.","أود سداد فاتورتي وتسليم الغرفة."),p("Puis-je payer par carte bancaire ?","هل يمكنني الدفع بالبطاقة المصرفية؟"),p("Pourriez-vous vérifier le détail de la facture ?","هل يمكنك التحقق من تفاصيل الفاتورة؟"),p("La taxe de séjour figure sur la dernière ligne.","تظهر ضريبة الإقامة في السطر الأخير."),p("Pouvez-vous garder mes bagages après mon départ ?","هل يمكنكم الاحتفاظ بأمتعتي بعد المغادرة؟")]},
 {id:"securite",fr:"Sécurité et urgence",ar:"السلامة والطوارئ",tag:"Consignes",image:"concierge",phrases:[p("Les sorties de secours sont indiquées à chaque étage.","مخارج الطوارئ موضحة في كل طابق."),p("En cas d’alarme, n’utilisez pas l’ascenseur.","عند سماع الإنذار، لا تستخدم المصعد."),p("Composez le zéro pour joindre la réception en urgence.","اطلب الرقم صفر للاتصال بالاستقبال في حالة الطوارئ."),p("Veuillez suivre les consignes du personnel.","يرجى اتباع تعليمات الموظفين."),p("Le point de rassemblement se trouve devant l’entrée principale.","تقع نقطة التجمع أمام المدخل الرئيسي.")]}
];

const objectRooms:ObjectRoom[]=[
 {id:"reception",fr:"À la réception",ar:"في الاستقبال",image:"hero",objects:[{fr:"La carte de chambre",ar:"بطاقة الغرفة",note:"تفتح باب الغرفة",Icon:CreditCard},{fr:"La clé",ar:"المفتاح",note:"مفتاح تقليدي للغرفة",Icon:KeyRound},{fr:"La sonnette",ar:"جرس الاستقبال",note:"لطلب انتباه الموظف",Icon:Bell},{fr:"Le terminal de paiement",ar:"جهاز الدفع",note:"لدفع الفاتورة بالبطاقة",Icon:CircleDollarSign},{fr:"Le téléphone",ar:"الهاتف",note:"للاتصالات الداخلية",Icon:Phone},{fr:"Le reçu",ar:"الإيصال",note:"إثبات عملية الدفع",Icon:BadgeCheck}]},
 {id:"chambre",fr:"Dans la chambre",ar:"داخل الغرفة",image:"room",objects:[{fr:"Le lit",ar:"السرير",note:"قطعة النوم الرئيسية",Icon:BedDouble},{fr:"L’oreiller",ar:"الوسادة",note:"يوضع تحت الرأس",Icon:Sparkles},{fr:"Le coffre-fort",ar:"الخزنة",note:"لحفظ المقتنيات",Icon:ShieldCheck},{fr:"Le téléphone de chambre",ar:"هاتف الغرفة",note:"للاتصال بالاستقبال",Icon:Phone},{fr:"La climatisation",ar:"تكييف الهواء",note:"للتحكم في حرارة الغرفة",Icon:Wind},{fr:"Le réseau Wi-Fi",ar:"شبكة الواي فاي",note:"للاتصال بالإنترنت",Icon:Wifi}]},
 {id:"bagages",fr:"Bagages et conciergerie",ar:"الأمتعة وخدمة النزلاء",image:"concierge",objects:[{fr:"La valise",ar:"الحقيبة الكبيرة",note:"لحمل الملابس والأغراض",Icon:Luggage},{fr:"Le chariot à bagages",ar:"عربة الأمتعة",note:"لنقل الحقائب",Icon:ConciergeBell},{fr:"La consigne à bagages",ar:"مكان حفظ الأمتعة",note:"لحفظ الحقائب مؤقتًا",Icon:ShieldCheck},{fr:"L’étiquette à bagages",ar:"بطاقة تعريف الحقيبة",note:"لتحديد صاحب الحقيبة",Icon:BadgeCheck}]},
 {id:"entretien",fr:"Entretien et linge",ar:"التنظيف والملابس",image:"housekeeping",objects:[{fr:"La serviette",ar:"المنشفة",note:"للتجفيف",Icon:Sparkles},{fr:"Le drap",ar:"ملاءة السرير",note:"يُفرش على السرير",Icon:BedDouble},{fr:"Le cintre",ar:"علاقة الملابس",note:"لتعليق الملابس",Icon:Shirt},{fr:"Le sac à linge",ar:"كيس الغسيل",note:"لجمع الملابس المرسلة للغسيل",Icon:WashingMachine},{fr:"Le chariot de ménage",ar:"عربة التنظيف",note:"لنقل مستلزمات النظافة",Icon:Sparkles}]},
 {id:"restaurant",fr:"Au restaurant",ar:"في المطعم",image:"restaurant",objects:[{fr:"Le plateau",ar:"الصينية",note:"لحمل الطعام",Icon:UtensilsCrossed},{fr:"La tasse",ar:"الفنجان",note:"لتقديم المشروبات الساخنة",Icon:UtensilsCrossed},{fr:"Les couverts",ar:"أدوات المائدة",note:"الشوكة والسكين والملعقة",Icon:UtensilsCrossed},{fr:"La serviette de table",ar:"منديل المائدة",note:"يوضع بجانب الطبق",Icon:Sparkles}]}
];

const dialogues:Dialogue[]=[
 {id:"booking",fr:"Réserver une chambre",ar:"حجز غرفة",context:"مكالمة بين نزيل وموظف الحجز",lines:[{role:"Client",fr:"Bonjour, je voudrais réserver une chambre pour le week-end prochain.",ar:"مرحبًا، أود حجز غرفة لعطلة نهاية الأسبوع القادمة."},{role:"Réceptionniste",fr:"Bien sûr. Pour combien de personnes et pour combien de nuits ?",ar:"بالتأكيد. لكم شخصًا وكم ليلة؟"},{role:"Client",fr:"Pour une personne, du vendredi au dimanche.",ar:"لشخص واحد، من الجمعة إلى الأحد."},{role:"Réceptionniste",fr:"Nous avons une chambre simple et une chambre double disponibles.",ar:"لدينا غرفة مفردة وغرفة مزدوجة متاحتان."},{role:"Client",fr:"Je préfère la chambre double. Le petit-déjeuner est-il inclus ?",ar:"أفضل الغرفة المزدوجة. هل الإفطار مشمول؟"},{role:"Réceptionniste",fr:"Oui, le petit-déjeuner est compris dans ce tarif.",ar:"نعم، الإفطار مشمول في هذا السعر."},{role:"Client",fr:"Parfait. Je vais prendre cette chambre.",ar:"ممتاز. سأحجز هذه الغرفة."},{role:"Réceptionniste",fr:"Votre réservation est confirmée. Vous recevrez un courriel dans quelques minutes.",ar:"تم تأكيد حجزك. ستصلك رسالة بريد إلكتروني خلال دقائق."}]},
 {id:"problem",fr:"Signaler un problème",ar:"الإبلاغ عن مشكلة",context:"محادثة مع الاستقبال من داخل الغرفة",lines:[{role:"Client",fr:"Bonsoir, je vous appelle de la chambre 408.",ar:"مساء الخير، أتصل بكم من الغرفة 408."},{role:"Réceptionniste",fr:"Bonsoir, monsieur. Comment puis-je vous aider ?",ar:"مساء الخير يا سيدي. كيف يمكنني مساعدتك؟"},{role:"Client",fr:"La climatisation ne fonctionne pas et la chambre est trop chaude.",ar:"التكييف لا يعمل والغرفة حارة جدًا."},{role:"Réceptionniste",fr:"Je suis désolé pour ce désagrément. Je vais envoyer un technicien.",ar:"أعتذر عن هذا الإزعاج. سأرسل فنيًا."},{role:"Client",fr:"Savez-vous combien de temps cela prendra ?",ar:"هل تعرف كم سيستغرق ذلك؟"},{role:"Réceptionniste",fr:"Il sera devant votre porte dans environ dix minutes.",ar:"سيكون أمام بابك خلال نحو عشر دقائق."},{role:"Client",fr:"Merci. Je vous rappellerai si le problème persiste.",ar:"شكرًا. سأتصل بكم مجددًا إذا استمرت المشكلة."},{role:"Réceptionniste",fr:"N’hésitez pas. Nous pourrons aussi vous proposer une autre chambre.",ar:"لا تتردد. يمكننا أيضًا أن نقترح عليك غرفة أخرى."}]},
 {id:"checkout",fr:"Régler la note",ar:"سداد الفاتورة والمغادرة",context:"محادثة كاملة عند مكتب الاستقبال",lines:[{role:"Client",fr:"Bonjour, je voudrais libérer la chambre 215.",ar:"مرحبًا، أود تسجيل المغادرة من الغرفة 215."},{role:"Réceptionniste",fr:"Très bien. Avez-vous utilisé le service de blanchisserie ?",ar:"حسنًا. هل استخدمت خدمة الغسيل؟"},{role:"Client",fr:"Oui, une seule fois, mardi matin.",ar:"نعم، مرة واحدة فقط صباح الثلاثاء."},{role:"Réceptionniste",fr:"Le service figure bien sur votre facture. Souhaitez-vous la vérifier ?",ar:"الخدمة مدرجة بالفعل في فاتورتك. هل ترغب في مراجعتها؟"},{role:"Client",fr:"Oui, s’il vous plaît. Je paierai ensuite par carte.",ar:"نعم من فضلك. سأدفع بعد ذلك بالبطاقة."},{role:"Réceptionniste",fr:"Voici le détail. Le montant total est de quatre cent vingt euros.",ar:"هذه التفاصيل. المبلغ الإجمالي أربعمئة وعشرون يورو."},{role:"Client",fr:"Tout est correct. Puis-je laisser mes bagages jusqu’à quinze heures ?",ar:"كل شيء صحيح. هل يمكنني ترك أمتعتي حتى الساعة الثالثة؟"},{role:"Réceptionniste",fr:"Bien sûr. Le bagagiste va les déposer à la consigne.",ar:"بالتأكيد. سيضعها موظف الأمتعة في غرفة الحفظ."}]}
];

const navItems=[{id:"departments",fr:"Situations",ar:"أقسام الفندق",Icon:ConciergeBell},{id:"objects",fr:"Objets",ar:"المفردات والأدوات",Icon:KeyRound},{id:"dialogues",fr:"Dialogues",ar:"المحادثات",Icon:MessageSquareText}] as const;

export default function HotelPage(){
 const [view,setView]=useState<(typeof navItems)[number]["id"]>("departments");
 const [activeDepartment,setActiveDepartment]=useState("reservation");
 const [activeObjectRoom,setActiveObjectRoom]=useState("reception");
 const [activeDialogue,setActiveDialogue]=useState("booking");
 const [query,setQuery]=useState("");
 const detailRef=useRef<HTMLElement>(null);
 const currentDepartment=departments.find(item=>item.id===activeDepartment)??departments[0];
 const currentObjectRoom=objectRooms.find(item=>item.id===activeObjectRoom)??objectRooms[0];
 const currentDialogue=dialogues.find(item=>item.id===activeDialogue)??dialogues[0];
 const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase("fr");return q?departments.filter(item=>`${item.fr} ${item.ar} ${item.tag}`.toLocaleLowerCase("fr").includes(q)):departments},[query]);
 const speak=(text:string)=>void speakFrench(text,{rate:.76});
 const selectAndScroll=(setter:(id:string)=>void,id:string)=>{setter(id);window.setTimeout(()=>detailRef.current?.scrollIntoView({behavior:"smooth",block:"start"}),0)};

 return <main className="hotel-world" dir="rtl">
  <header className="hotel-topbar"><Link href="/kingdom" aria-label="العودة إلى واجهة القلعة"><ArrowRight/></Link><div><ConciergeBell/><span><strong>L’HÔTEL</strong><small>الفندق التعليمي</small></span></div><div className="hotel-open"><i/> Réception 24 h / 24</div></header>
  <section className="hotel-hero"><img src="/hotel-v1/hero.webp" alt="ردهة استقبال فندق فرنسي فخم"/><div className="hotel-hero-shade"/><div className="hotel-hero-copy"><span><BadgeCheck/> Parcours de français hôtelier</span><h1>Bienvenue<br/><em>à l’Hôtel</em></h1><p>تعلّم الفرنسية العملية منذ الحجز وحتى المغادرة، داخل فندق تفاعلي واقعي ومنظم.</p><button onClick={()=>document.querySelector(".hotel-main-nav")?.scrollIntoView({behavior:"smooth"})}>ابدأ الجولة <ArrowRight/></button></div><div className="hotel-hero-stats"><div><b>{departments.length}</b><span>موقفًا فندقيًا</span></div><div><b>{departments.reduce((n,item)=>n+item.phrases.length,0)}</b><span>جملة عملية</span></div><div><b>{objectRooms.reduce((n,item)=>n+item.objects.length,0)}</b><span>مفردة أساسية</span></div></div></section>
  <nav className="hotel-main-nav" aria-label="أقسام تعلم الفندق">{navItems.map(({id,fr,ar,Icon})=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><Icon/><span><strong>{fr}</strong><small>{ar}</small></span></button>)}</nav>

  {view==="departments"&&<section className="hotel-learning-section"><div className="hotel-section-title"><span>01 · Situations professionnelles</span><h2>أقسام الفندق ومواقف الإقامة</h2><p>اختر موقفًا؛ ستنتقل تلقائيًا إلى جمله، واضغط على أي جملة لسماع نطقها الفرنسي.</p></div><label className="hotel-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="ابحث عن موقف…  Rechercher une situation"/></label><div className="hotel-department-grid">{filtered.map((item,index)=><button key={item.id} className={activeDepartment===item.id?"active":""} onClick={()=>selectAndScroll(setActiveDepartment,item.id)} style={{backgroundImage:`linear-gradient(180deg,transparent 18%,#071d18e8 100%),url(/hotel-v1/${item.image}.webp)`}}><i>{String(index+1).padStart(2,"0")}</i><span><small>{item.tag}</small><strong dir="ltr">{item.fr}</strong><b>{item.ar}</b></span><ArrowRight/></button>)}</div><article ref={detailRef} className="hotel-detail-card"><header><img src={`/hotel-v1/${currentDepartment.image}.webp`} alt={currentDepartment.ar}/><div><span>{currentDepartment.tag}</span><h3 dir="ltr">{currentDepartment.fr}</h3><p>{currentDepartment.ar}</p></div></header><div className="hotel-phrase-list">{currentDepartment.phrases.map((item,index)=><button key={item.fr} onClick={()=>speak(item.fr)}><i>{String(index+1).padStart(2,"0")}</i><span><strong dir="ltr">{item.fr}</strong><small>{item.ar}</small></span><Volume2/></button>)}</div></article></section>}

  {view==="objects"&&<section className="hotel-learning-section"><div className="hotel-section-title"><span>02 · Vocabulaire de l’hôtel</span><h2>المفردات والأدوات حسب المكان</h2><p>كل كلمة موضوعة في مكان استخدامها الحقيقي، مع شرح مختصر ونطق مستقل.</p></div><div className="hotel-object-tabs">{objectRooms.map(item=><button key={item.id} className={activeObjectRoom===item.id?"active":""} onClick={()=>selectAndScroll(setActiveObjectRoom,item.id)}><strong dir="ltr">{item.fr}</strong><small>{item.ar}</small></button>)}</div><article ref={detailRef} className="hotel-object-room"><header><img src={`/hotel-v1/${currentObjectRoom.image}.webp`} alt={currentObjectRoom.ar}/><div><span>VOCABULAIRE</span><h3 dir="ltr">{currentObjectRoom.fr}</h3><p>{currentObjectRoom.ar}</p></div></header><div className="hotel-object-grid">{currentObjectRoom.objects.map(({fr,ar,note,Icon},index)=><button key={fr} onClick={()=>speak(fr)}><i>{String(index+1).padStart(2,"0")}</i><Icon/><span><strong dir="ltr">{fr}</strong><b>{ar}</b><small>{note}</small></span><Volume2/></button>)}</div></article></section>}

  {view==="dialogues"&&<section className="hotel-learning-section"><div className="hotel-section-title"><span>03 · Conversations guidées</span><h2>محادثات فندقية كاملة</h2><p>مواقف متسلسلة وغير مكررة؛ اضغط على كل سطر لسماع نطقه منفصلًا.</p></div><div className="hotel-dialogue-tabs">{dialogues.map(item=><button key={item.id} className={activeDialogue===item.id?"active":""} onClick={()=>selectAndScroll(setActiveDialogue,item.id)}><MessageSquareText/><span><strong dir="ltr">{item.fr}</strong><small>{item.ar}</small></span></button>)}</div><article ref={detailRef} className="hotel-dialogue-card"><header><span>CONVERSATION</span><h3 dir="ltr">{currentDialogue.fr}</h3><p>{currentDialogue.context}</p></header><div className="hotel-dialogue-lines">{currentDialogue.lines.map((line,index)=><button key={`${line.fr}-${index}`} className={line.role==="Client"?"guest":"staff"} onClick={()=>speak(line.fr)}><i>{line.role}</i><span><strong dir="ltr">{line.fr}</strong><small>{line.ar}</small></span><Volume2/></button>)}</div></article></section>}

  <section className="hotel-sources"><div><ShieldCheck/><span><strong>محتوى فندقي عملي مدقّق</strong><small>Terminologie professionnelle et français courant</small></span></div><p>صيغ التعلم مستندة إلى الاستعمال الفندقي الفرنسي المعياري، مع مراعاة وضوح العبارة وطبيعية الموقف.</p><div><a href="https://www.service-public.fr/particuliers/vosdroits/F2050" target="_blank" rel="noreferrer">Service-Public.fr · Hôtel</a><a href="https://www.france.fr/" target="_blank" rel="noreferrer">France.fr · Tourisme</a><a href="https://www.larousse.fr/dictionnaires/francais" target="_blank" rel="noreferrer">Larousse · Dictionnaire</a></div></section>
 </main>;
}
