"use client";
import {useState} from "react";
import {BookOpen,Bot,Castle,Flame,Gem,KeyRound,Menu,ScrollText,ShoppingBag,Sparkles,Trophy,Volume2} from "lucide-react";
import Shield from "@/components/Shield";
import WorldCard from "@/components/WorldCard";
import {lesson,worlds} from "@/data/worlds";
export default function Home(){const[open,setOpen]=useState(false);const[index,setIndex]=useState(0);const word=lesson[index];const speak=()=>{const u=new SpeechSynthesisUtterance(word.fr);u.lang="fr-FR";speechSynthesis.speak(u)};return <main>
<header className="topbar"><div className="brand"><Shield small/><div><h1>Le Château des Langues</h1><span>القلعة اللغوية</span></div></div><nav><a className="active"><Castle size={18}/>الرئيسية</a><a><ScrollText size={18}/>المسار</a><a><BookOpen size={18}/>الدروس</a><a><Bot size={18}/>المعلم</a><a><ShoppingBag size={18}/>المتجر</a></nav><div className="wallet"><span>🪙 2,450</span><span><Gem size={16}/>120</span><button><Menu/></button></div></header>
<section className="dashboard"><aside className="profile panel"><div className="avatar">ف</div><h2>فارس القلعة</h2><p>المستوى 23</p><div className="progress"><span style={{width:"78%"}}/></div><div className="metric"><Flame/><div><b>15 يومًا</b><span>الأيام المتتالية</span></div></div><div className="metric"><Sparkles/><div><b>12,580 XP</b><span>نقاط الخبرة</span></div></div><div className="metric"><KeyRound/><div><b>18 / 50</b><span>مفاتيح القلعة</span></div></div><div className="metric"><Trophy/><div><b>7 أوسمة</b><span>الإنجازات</span></div></div><div className="castle-card"><span>بطاقة القلعة</span><Shield/></div></aside>
<section className="hero panel"><div className="hero-content"><Shield/><span>Bienvenue dans</span><h2>القلعة اللغوية</h2><p>Chaque mot ouvre une porte.</p><small>كل كلمة تفتح بابًا.</small><button onClick={()=>setOpen(true)}>ابدأ رحلتك</button></div></section>
<aside className="daily panel"><h3>تقدمك اليوم</h3><div className="ring"><span>60%</span></div><h4>مهام اليوم</h4><ul><li>✅ إكمال 3 دروس</li><li>✅ تعلّم 12 كلمة</li><li>✅ محادثة قصيرة</li><li>◯ اختبار سريع</li></ul><button>عرض كل المهام</button></aside></section>
<section className="worlds"><div className="section-title"><div><span>كل العوالم مفتوحة</span><h2>عوالم القلعة</h2></div><p>اختر أي عالم وابدأ مباشرة من A1 حتى C2.</p></div><div className="world-grid">{worlds.map(w=><WorldCard key={w.id} world={w}/>)}</div></section>
<section className="lower"><article className="panel card"><div><span>الدرس الحالي</span><h2>بوابة التحيات</h2><p>تعلّم التحية والتعارف وابدأ أول محادثة فرنسية.</p><button onClick={()=>setOpen(true)}>ابدأ الدرس</button></div><div className="big">🗣️</div></article><article className="panel card"><div className="big">🧙‍♂️</div><div><span>Maître Louis</span><h2>Bonjour !</h2><p>مستعد لمواصلة رحلتك اللغوية اليوم؟</p><button>تحدث مع المعلم</button></div></article></section>
{open&&<div className="modal" onClick={()=>setOpen(false)}><div className="lesson-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(false)}>×</button><span>بوابة التحيات · الدرس الأول</span><h2>{word.fr}</h2><button className="sound" onClick={speak}><Volume2/> استمع للنطق</button><h3>{word.ar}</h3><div className="example"><p>{word.example}</p><span>{word.translation}</span></div><div className="actions"><button onClick={()=>setIndex((index-1+lesson.length)%lesson.length)}>السابق</button><button onClick={()=>setIndex((index+1)%lesson.length)}>التالي</button></div></div></div>}<footer>Le Château des Langues — الإصدار 0.1</footer></main>}
