"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowRight, BookOpen, CalendarClock, ChevronLeft, CircleParking, Clock3, Headphones, Info, Luggage, MapPinned, Menu, Route, ScanLine, Search, Ticket, TrainFront, Volume2 } from "lucide-react";

const sections = [
  { id: "arrival", fr: "Arrivée à la gare", ar: "الوصول إلى المحطة", icon: MapPinned, image: "https://unsplash.com/photos/vsEkHU5Vpn8/download?force=true&w=1600" },
  { id: "ticket", fr: "Acheter un billet", ar: "شراء التذكرة", icon: Ticket, image: "https://unsplash.com/photos/TnLUf0kSJEI/download?force=true&w=1600" },
  { id: "board", fr: "Tableau des départs", ar: "لوحة المغادرات", icon: CalendarClock, image: "https://unsplash.com/photos/p022og65qHQ/download?force=true&w=1600" },
  { id: "platform", fr: "Le quai", ar: "الرصيف", icon: CircleParking, image: "https://unsplash.com/photos/guLjfcsKC-o/download?force=true&w=1600" },
  { id: "control", fr: "Contrôle du billet", ar: "فحص التذكرة", icon: ScanLine, image: "https://unsplash.com/photos/QbxnM4Hxz6c/download?force=true&w=1600" },
  { id: "boarding", fr: "Monter dans le train", ar: "الصعود إلى القطار", icon: TrainFront, image: "https://unsplash.com/photos/XAezAuhVHts/download?force=true&w=1600" },
  { id: "inside", fr: "Dans le train", ar: "داخل القطار", icon: Luggage, image: "https://unsplash.com/photos/rt6YfAyWAg0/download?force=true&w=1600" },
  { id: "connection", fr: "Arrivée et correspondance", ar: "الوصول وتغيير القطار", icon: Route, image: "https://unsplash.com/photos/dUJWfpKyIYc/download?force=true&w=1600" },
];

type Phrase = [string,string];
const common: Phrase[] = [
  ["Pouvez-vous m'aider, s'il vous plaît ?","هل يمكنك مساعدتي من فضلك؟"],["Je ne comprends pas l'annonce.","لا أفهم الإعلان."],["Pouvez-vous parler plus lentement ?","هل يمكنك التحدث ببطء أكثر؟"],["Est-ce que je suis au bon endroit ?","هل أنا في المكان الصحيح؟"],["Combien de temps faut-il attendre ?","كم يجب أن أنتظر؟"],["Où se trouvent les toilettes ?","أين توجد دورات المياه؟"],["Y a-t-il un ascenseur ?","هل يوجد مصعد؟"],["Merci pour votre aide.","شكرًا لمساعدتك."],["Excusez-moi, j'ai une question.","عذرًا، لدي سؤال."],["C'est loin d'ici ?","هل هو بعيد من هنا؟"]
];
const specific: Record<string,Phrase[]> = {
arrival:[["Bonjour, où se trouve le hall principal ?","مرحبًا، أين توجد الصالة الرئيسية؟"],["Le hall est juste devant vous.","الصالة أمامك مباشرة."],["Où puis-je consulter les départs ?","أين يمكنني رؤية مواعيد المغادرة؟"],["Je viens d'arriver à la gare.","لقد وصلت للتو إلى المحطة."],["Où est l'entrée principale ?","أين المدخل الرئيسي؟"],["La consigne à bagages est-elle ouverte ?","هل مكتب حفظ الأمتعة مفتوح؟"],["Je cherche le point d'information.","أبحث عن مكتب المعلومات."],["Où puis-je acheter de l'eau ?","أين يمكنني شراء الماء؟"],["La gare ferme à quelle heure ?","في أي ساعة تغلق المحطة؟"],["Il y a beaucoup de monde aujourd'hui.","هناك ازدحام كبير اليوم."],["Je dois rejoindre le quai rapidement.","يجب أن أصل إلى الرصيف بسرعة."],["Le panneau est près de l'entrée.","اللوحة قرب المدخل."],["Prenez l'escalator à gauche.","خذ السلم المتحرك إلى اليسار."],["Le guichet se trouve au fond du hall.","شباك التذاكر في نهاية الصالة."]],
 ticket:[["Je voudrais un billet pour Lyon, s'il vous plaît.","أريد تذكرة إلى ليون من فضلك."],["Aller simple ou aller-retour ?","ذهاب فقط أم ذهاب وعودة؟"],["À quelle heure part le prochain train ?","متى ينطلق القطار القادم؟"],["Je préfère une place près de la fenêtre.","أفضل مقعدًا بجانب النافذة."],["Combien coûte le billet ?","كم سعر التذكرة؟"],["Puis-je payer par carte ?","هل يمكنني الدفع بالبطاقة؟"],["Avez-vous un tarif moins cher ?","هل لديكم سعر أرخص؟"],["Je voyage avec un enfant.","أسافر مع طفل."],["Je voudrais modifier ma réservation.","أريد تعديل حجزي."],["Puis-je annuler ce billet ?","هل يمكنني إلغاء هذه التذكرة؟"],["Le billet est-il remboursable ?","هل التذكرة قابلة للاسترجاع؟"],["Je n'ai pas reçu mon billet électronique.","لم تصلني تذكرتي الإلكترونية."],["Voici ma pièce d'identité.","هذه هويتي."],["Je voudrais voyager en première classe.","أريد السفر بالدرجة الأولى."]],
 board:[["Mon train est-il à l'heure ?","هل قطاري في موعده؟"],["Il a quinze minutes de retard.","متأخر خمس عشرة دقيقة."],["Quel est le numéro du train ?","ما رقم القطار؟"],["Le quai a-t-il changé ?","هل تغير الرصيف؟"],["Le train est annulé.","القطار ملغى."],["Le départ est prévu à dix heures vingt.","المغادرة مقررة الساعة العاشرة وعشرين دقيقة."],["L'arrivée est affichée sur l'écran.","الوصول ظاهر على الشاشة."],["Je ne trouve pas ma destination.","لا أجد وجهتي."],["Que signifie cette mention ?","ماذا تعني هذه العبارة؟"],["Le train est annoncé voie douze.","أُعلن أن القطار على السكة 12."],["L'embarquement commence bientôt.","سيبدأ الصعود قريبًا."],["Le train change de voie.","القطار يغير السكة."],["Regardez la ligne en jaune.","انظر إلى السطر الأصفر."],["L'information vient d'être mise à jour.","تم تحديث المعلومة للتو."]],
 platform:[["De quel quai part le train ?","من أي رصيف ينطلق القطار؟"],["Il part du quai numéro six.","ينطلق من الرصيف رقم ستة."],["Le quai est-il loin d'ici ?","هل الرصيف بعيد من هنا؟"],["Restez derrière la ligne jaune.","ابق خلف الخط الأصفر."],["Le train va entrer en gare.","سيدخل القطار إلى المحطة."],["Cette partie du quai est fermée.","هذا الجزء من الرصيف مغلق."],["Où se trouve la voiture huit ?","أين توجد العربة رقم 8؟"],["Le train est très long.","القطار طويل جدًا."],["Avancez vers le milieu du quai.","تقدم نحو منتصف الرصيف."],["La première classe est à l'avant.","الدرجة الأولى في المقدمة."],["Faites attention à la marche.","انتبه للدرجة."],["Le quai est couvert.","الرصيف مغطى."],["Nous attendons l'autorisation de départ.","ننتظر إذن المغادرة."],["Les voyageurs doivent s'éloigner du bord.","يجب على المسافرين الابتعاد عن الحافة."]],
 control:[["Votre billet, s'il vous plaît.","تذكرتك من فضلك."],["Voici mon billet électronique.","هذه تذكرتي الإلكترونية."],["Merci, bon voyage.","شكرًا، رحلة سعيدة."],["Le code ne fonctionne pas.","الرمز لا يعمل."],["Augmentez la luminosité de votre écran.","ارفع سطوع الشاشة."],["Puis-je voir votre pièce d'identité ?","هل يمكنني رؤية هويتك؟"],["Votre billet est valable aujourd'hui.","تذكرتك صالحة اليوم."],["Cette place est réservée.","هذا المقعد محجوز."],["Vous êtes dans la mauvaise voiture.","أنت في العربة الخطأ."],["Votre abonnement a expiré.","اشتراكك منتهي."],["Le contrôle est terminé.","انتهى الفحص."],["Gardez votre billet jusqu'à l'arrivée.","احتفظ بتذكرتك حتى الوصول."],["Ce billet n'est pas échangeable.","هذه التذكرة غير قابلة للتبديل."],["Je vais vérifier votre réservation.","سأتحقق من حجزك."]],
 boarding:[["Est-ce le train pour Paris ?","هل هذا القطار المتجه إلى باريس؟"],["Oui, montez dans la voiture huit.","نعم، اصعد إلى العربة رقم ثمانية."],["Les portes vont fermer.","الأبواب ستغلق."],["Laissez descendre les voyageurs.","دع المسافرين ينزلون."],["Où est la porte la plus proche ?","أين أقرب باب؟"],["Montez rapidement, s'il vous plaît.","اصعد بسرعة من فضلك."],["Cette porte est hors service.","هذا الباب خارج الخدمة."],["Le train part dans deux minutes.","القطار يغادر بعد دقيقتين."],["Aidez-moi avec cette valise.","ساعدني في هذه الحقيبة."],["Il reste des places libres.","ما زالت هناك مقاعد شاغرة."],["Je dois changer de voiture.","يجب أن أغير العربة."],["La rampe est disponible ici.","المنحدر متاح هنا."],["Ne bloquez pas le passage.","لا تغلق الممر."],["Bienvenue à bord.","مرحبًا بكم على متن القطار."]],
 inside:[["Où se trouve mon siège ?","أين يوجد مقعدي؟"],["Votre siège est près de la fenêtre.","مقعدك بجانب النافذة."],["Puis-je mettre ma valise ici ?","هل أستطيع وضع حقيبتي هنا؟"],["Cette place est-elle libre ?","هل هذا المقعد شاغر؟"],["Je voudrais baisser le dossier.","أريد خفض مسند الظهر."],["Le Wi-Fi est-il gratuit ?","هل الواي فاي مجاني؟"],["Où se trouve la voiture-bar ?","أين عربة المقهى؟"],["Pouvez-vous baisser la musique ?","هل يمكنك خفض الموسيقى؟"],["Le prochain arrêt est Dijon.","المحطة القادمة ديجون."],["Le train roule à grande vitesse.","القطار يسير بسرعة عالية."],["Je vais descendre au prochain arrêt.","سأنزل في المحطة القادمة."],["Les toilettes sont au fond de la voiture.","دورات المياه في نهاية العربة."],["Le chargeur ne fonctionne pas.","الشاحن لا يعمل."],["Veuillez parler moins fort.","يرجى خفض الصوت."]],
 connection:[["Où dois-je changer de train ?","أين يجب أن أغير القطار؟"],["Vous changez à Dijon.","تغيّر القطار في ديجون."],["Vous avez vingt minutes pour la correspondance.","لديك عشرون دقيقة للتبديل."],["Ma correspondance est très courte.","وقت التبديل قصير جدًا."],["Le prochain train part du quai neuf.","القطار التالي يغادر من الرصيف 9."],["J'ai raté ma correspondance.","فاتني القطار المتصل."],["Où est la sortie ?","أين المخرج؟"],["Mon voyage se termine ici.","تنتهي رحلتي هنا."],["Je dois récupérer mes bagages.","يجب أن أستلم أمتعتي."],["Le train de correspondance est retardé.","القطار المتصل متأخر."],["Suivez les panneaux bleus.","اتبع اللوحات الزرقاء."],["Le quai est dans un autre bâtiment.","الرصيف في مبنى آخر."],["J'ai besoin d'un nouveau billet.","أحتاج إلى تذكرة جديدة."],["À quelle heure arrive le prochain train ?","متى يصل القطار القادم؟"]]
};
const dialogues: Record<string,Phrase[]> = Object.fromEntries(Object.entries(specific).map(([k,v])=>[k,[...v,...common]]));

const vocabGroups = {
  "La gare": [
["La gare","محطة القطار"],["Le hall","الصالة"],["L'entrée","المدخل"],["La sortie","المخرج"],["Le guichet","شباك التذاكر"],["Le point d'information","مكتب المعلومات"],["La salle d'attente","صالة الانتظار"],["La consigne","حفظ الأمتعة"],["Le distributeur","جهاز بيع التذاكر"],["L'escalator","السلم المتحرك"],["L'ascenseur","المصعد"],["L'escalier","الدرج"],["Le couloir","الممر"],["Les toilettes","دورات المياه"],["Le panneau","اللوحة"],["La signalisation","الإرشادات"],["Le parking","موقف السيارات"],["Le parvis","ساحة المحطة"],["La porte automatique","الباب الآلي"],["Le passage souterrain","الممر السفلي"]],
  "Billets et réservation": [
["Le billet","التذكرة"],["Le billet électronique","التذكرة الإلكترونية"],["La réservation","الحجز"],["L'aller simple","ذهاب فقط"],["L'aller-retour","ذهاب وعودة"],["Le tarif","السعر"],["La réduction","التخفيض"],["Le remboursement","الاسترجاع"],["L'échange","التبديل"],["La première classe","الدرجة الأولى"],["La seconde classe","الدرجة الثانية"],["La place assise","المقعد"],["Le numéro de siège","رقم المقعد"],["La voiture","العربة"],["Le reçu","الإيصال"],["La carte bancaire","البطاقة البنكية"],["Le paiement sans contact","الدفع اللاتلامسي"],["La pièce d'identité","الهوية"],["L'abonnement","الاشتراك"],["Le code QR","رمز الاستجابة السريعة"]],
  "Départs et horaires": [
["Le départ","المغادرة"],["L'arrivée","الوصول"],["L'horaire","الموعد"],["Le retard","التأخير"],["L'annulation","الإلغاء"],["Le tableau des départs","لوحة المغادرات"],["Le tableau des arrivées","لوحة الوصول"],["La destination","الوجهة"],["La provenance","جهة القدوم"],["Le numéro du train","رقم القطار"],["La voie","السكة"],["Le quai","الرصيف"],["La correspondance","تغيير القطار"],["Le terminus","المحطة الأخيرة"],["À l'heure","في الموعد"],["En retard","متأخر"],["En avance","مبكر"],["Le prochain train","القطار القادم"],["L'annonce","الإعلان"],["La mise à jour","التحديث"]],
  "Le train": [
["Le train","القطار"],["La locomotive","القاطرة"],["Le wagon","العربة"],["La voiture-bar","عربة المقهى"],["Le siège","المقعد"],["La fenêtre","النافذة"],["La porte","الباب"],["Le dossier","مسند الظهر"],["La tablette","الطاولة الصغيرة"],["Le porte-bagages","رف الأمتعة"],["Le couloir","الممر"],["La prise électrique","مقبس الكهرباء"],["Le Wi-Fi","الواي فاي"],["La climatisation","التكييف"],["Le contrôleur","مفتش التذاكر"],["Le conducteur","السائق"],["Le passager","الراكب"],["Le voyageur","المسافر"],["Le train régional","القطار الإقليمي"],["Le train à grande vitesse","القطار فائق السرعة"]],
  "Bagages et services": [
["La valise","الحقيبة"],["Le sac à dos","حقيبة الظهر"],["Le bagage à main","حقيبة اليد"],["Les bagages","الأمتعة"],["Le chariot","عربة الأمتعة"],["L'étiquette","ملصق الحقيبة"],["L'objet perdu","الغرض المفقود"],["Le service des objets trouvés","مكتب المفقودات"],["L'aide aux voyageurs","مساعدة المسافرين"],["La rampe","المنحدر"],["Le fauteuil roulant","الكرسي المتحرك"],["Le café","المقهى"],["Le kiosque","الكشك"],["La bouteille d'eau","زجاجة الماء"],["Le chargeur","الشاحن"],["La connexion Internet","اتصال الإنترنت"],["Le plan de la gare","خريطة المحطة"],["Le casier","الخزانة"],["Le service client","خدمة العملاء"],["L'urgence","الطوارئ"]],
  "Verbes utiles": [
["Arriver","يصل"],["Partir","يغادر"],["Attendre","ينتظر"],["Réserver","يحجز"],["Acheter","يشتري"],["Payer","يدفع"],["Annuler","يلغي"],["Modifier","يعدل"],["Rembourser","يسترجع"],["Monter","يصعد"],["Descendre","ينزل"],["Changer","يغيّر"],["Chercher","يبحث"],["Trouver","يجد"],["Rater","يفوّت"],["Valider","يعتمد/يمرر"],["Scanner","يمسح الرمز"],["Vérifier","يتحقق"],["Suivre","يتبع"],["Voyager","يسافر"]]
} as const;

const stories = [
  { title: "Karim à la gare", ar: "كريم في محطة القطار", text: "Karim arrive à la gare une heure avant le départ. Il achète son billet, consulte le tableau des départs et trouve le quai numéro quatre. Il monte dans le train et s'assoit près de la fenêtre." },
  { title: "Karim rate son train", ar: "كريم يفوّت القطار", text: "Karim arrive en retard à la gare. Quand il atteint le quai, les portes sont déjà fermées. Il va au guichet, explique la situation et réserve un autre train pour l'après-midi." },
];

export default function StationPage() {
  const [active, setActive] = useState("arrival");
  const [story, setStory] = useState(0);
  const [answer, setAnswer] = useState<number | null>(null);
  const [vocabTab,setVocabTab] = useState<keyof typeof vocabGroups>("La gare");
  const [search,setSearch] = useState("");
  const current = useMemo(() => sections.find((s) => s.id === active) ?? sections[0], [active]);
  const vocab = useMemo(()=>vocabGroups[vocabTab].filter(([fr,ar])=>`${fr} ${ar}`.toLowerCase().includes(search.toLowerCase())),[vocabTab,search]);
  const speak = (text: string) => { if (typeof window === "undefined") return; window.speechSynthesis.cancel(); const u = new SpeechSynthesisUtterance(text); u.lang = "fr-FR"; u.rate = 0.82; window.speechSynthesis.speak(u); };

  return <main className="station-world">
    <header className="station-topbar"><Link href="/kingdom" className="station-nav-icon" aria-label="Retour à la carte"><ArrowRight size={22}/></Link><div><span>محطة القطار</span><strong>La Gare Royale</strong></div><button className="station-nav-icon" aria-label="Menu"><Menu size={22}/></button></header>

    <section className="station-hero"><img src="https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=1800&q=92" alt="Gare ferroviaire avec train de voyageurs"/><div className="station-hero-shade"/><div className="station-hero-copy"><span><TrainFront size={18}/> Monde ouvert</span><h1>La Gare Royale</h1><p>جميع المراحل مفتوحة ويمكنك التنقل بينها بحرية.</p><button onClick={() => speak("Bienvenue à la gare royale. Toutes les étapes sont ouvertes.")}><Volume2 size={20}/> Écouter l'accueil</button></div></section>

    <section className="station-section-grid">{sections.map(({id, fr, ar, image, icon: Icon}, index) => <button key={id} onClick={() => { setActive(id); document.getElementById("station-lesson")?.scrollIntoView({behavior:"smooth"}); }} className={`station-section-card ${active === id ? "active" : ""}`}><img src={image} alt={fr}/><span className="station-card-index">{String(index + 1).padStart(2,"0")}</span><div className="station-card-copy"><span className="station-red-icon"><Icon size={21}/></span><strong>{fr}</strong><small>{ar}</small></div></button>)}</section>

    <section id="station-lesson" className="station-panel"><div className="station-panel-title"><div><span>{current.ar}</span><h2>{current.fr}</h2><small>{dialogues[active].length} phrases parlées</small></div><button onClick={() => speak(current.fr)}><Volume2 size={20}/></button></div><div className="station-lesson-layout"><img src={current.image} alt={current.fr}/><div className="station-dialogues">{dialogues[active].map(([fr, ar]) => <button key={fr} onClick={() => speak(fr)}><span><strong>{fr}</strong><small>{ar}</small></span><Volume2 size={18}/></button>)}</div></div></section>

    <section className="station-panel"><div className="station-panel-title"><div><span>أكثر من 120 مفردة أساسية</span><h2>Vocabulaire essentiel</h2></div><BookOpen size={24}/></div><div className="station-vocab-toolbar"><div className="station-vocab-tabs">{Object.keys(vocabGroups).map(group=><button key={group} className={vocabTab===group?"active":""} onClick={()=>setVocabTab(group as keyof typeof vocabGroups)}>{group}</button>)}</div><label><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher une expression..."/></label></div><div className="station-vocab-grid">{vocab.map(([fr, ar]) => <article key={fr}><span className="station-vocab-icon"><BookOpen size={25}/></span><div><strong>{fr}</strong><small>{ar}</small></div><button onClick={() => speak(fr)}><Volume2 size={17}/></button></article>)}</div></section>

    <section className="station-stories"><div className="station-story-visual"><img src={story === 0 ? sections[0].image : sections[3].image} alt={stories[story].title}/><span>Histoire A1+</span></div><div className="station-story-copy"><span>قصص الرحلة</span><h2>{stories[story].title}</h2><small>{stories[story].ar}</small><p>{stories[story].text}</p><div className="station-story-actions"><button onClick={() => speak(stories[story].text)}><Headphones size={19}/> Écouter</button><button onClick={() => setStory(story === 0 ? 1 : 0)}><ChevronLeft size={18}/> Histoire suivante</button></div></div></section>

    <section className="station-panel station-quiz"><div className="station-panel-title"><div><span>اختبار سريع</span><h2>Compréhension</h2></div><Info size={24}/></div><h3>Où Karim trouve-t-il les informations sur son train ?</h3><p>أين يجد كريم معلومات قطاره؟</p><div className="station-answer-grid">{["Au café", "Sur le tableau des départs", "Dans le taxi"].map((x,i)=><button key={x} className={answer===i?(i===1?"correct":"wrong"):""} onClick={()=>setAnswer(i)}>{x}</button>)}</div></section>

    <footer className="station-mini-progress" aria-label="Progression discrète"><span>Progression du monde</span><div><i style={{width:"3%"}}/></div><small>3%</small></footer>
  </main>;
}
