import {a1Foundations} from "./data/a1-foundations";
import {a1Determiners} from "./data/a1-determiners";
import {a1PresentVerbs} from "./data/a1-present-verbs";
import {a1Description} from "./data/a1-description";
import {a1SentenceForms} from "./data/a1-sentence-forms";
import {a1TimeAndTenses} from "./data/a1-time-and-tenses";
import {a1SpaceAndExpression} from "./data/a1-space-and-expression";
import {a1ActionsAndReference} from "./data/a1-actions-and-reference";
import {a2PastNarration} from "./data/a2-past-narration";
import {a2FutureAndTime} from "./data/a2-future-and-time";
import {a2ObjectPronouns} from "./data/a2-object-pronouns";
import {a2ReferenceAndIdentity} from "./data/a2-reference-and-identity";
import {a2DescriptionAndComparison} from "./data/a2-description-and-comparison";
import {a2SentenceNuance} from "./data/a2-sentence-nuance";
import {a2InteractionAndLinking} from "./data/a2-interaction-and-linking";
import {b1Narration} from "./data/b1-narration";
import {b1FutureCondition} from "./data/b1-future-condition";
import {b1Subjunctive} from "./data/b1-subjunctive";
import {b1Pronouns} from "./data/b1-pronouns";
import {b1Relatives} from "./data/b1-relatives";
import {b1Transformations} from "./data/b1-transformations";
import {b1Discourse} from "./data/b1-discourse";
import {b1Nuance} from "./data/b1-nuance";
import {b2TenseNarration} from "./data/b2-tense-narration";
import {b2ConditionModal} from "./data/b2-condition-modal";
import {b2Subjunctive} from "./data/b2-subjunctive";
import {b2VerbalForms} from "./data/b2-verbal-forms";
import {b2Pronouns} from "./data/b2-pronouns";
import {b2RelativesPrepositions} from "./data/b2-relatives-prepositions";
import {b2Transformations} from "./data/b2-transformations";
import {b2ReportedSpeech} from "./data/b2-reported-speech";
import {b2LogicalRelations} from "./data/b2-logical-relations";
import {b2NegationDetermination} from "./data/b2-negation-determination";
import {b2Argumentation} from "./data/b2-argumentation";
import {b2CohesionRegister} from "./data/b2-cohesion-register";
import {c1TemporalViewpoint} from "./data/c1-temporal-viewpoint";
import {c1LiteraryForms} from "./data/c1-literary-forms";
import {c1Counterfactual} from "./data/c1-counterfactual";
import {c1MoodSelection} from "./data/c1-mood-selection";
import {c1EpistemicModality} from "./data/c1-epistemic-modality";
import {c1NonfiniteForms} from "./data/c1-nonfinite-forms";
import {c1DetachedConstructions} from "./data/c1-detached-constructions";
import {c1ComplexSubordination} from "./data/c1-complex-subordination";
import {c1ReferenceSystem} from "./data/c1-reference-system";
import {c1DeterminationAgreement} from "./data/c1-determination-agreement";
import {c1FocusWordOrder} from "./data/c1-focus-word-order";
import {c1PolyphonyReported} from "./data/c1-polyphony-reported";
import {c1ArgumentLogic} from "./data/c1-argument-logic";
import {c1TextCohesion} from "./data/c1-text-cohesion";
import {c1WordFormationCollocation} from "./data/c1-word-formation-collocation";
import {c1RegisterEditing} from "./data/c1-register-editing";

export type GrammarRole="subject"|"verb"|"object"|"marker"|"adjective";
export type GrammarExample={fr:string;ar:string;parts:{text:string;role:GrammarRole}[]};
export type GrammarLesson={id:string;number:number;titleFr:string;titleAr:string;category:string;summary:string;rule:string;formula:string;examples:GrammarExample[];correct:string;correctAr:string;incorrect:string;incorrectReason:string;note:string};

export const a1Lessons:GrammarLesson[]=[...a1Foundations,...a1Determiners,...a1PresentVerbs,...a1Description,...a1SentenceForms,...a1TimeAndTenses,...a1SpaceAndExpression,...a1ActionsAndReference];
export const a2Lessons:GrammarLesson[]=[...a2PastNarration,...a2FutureAndTime,...a2ObjectPronouns,...a2ReferenceAndIdentity,...a2DescriptionAndComparison,...a2SentenceNuance,...a2InteractionAndLinking];
export const b1Lessons:GrammarLesson[]=[...b1Narration,...b1FutureCondition,...b1Subjunctive,...b1Pronouns,...b1Relatives,...b1Transformations,...b1Discourse,...b1Nuance];
export const b2Lessons:GrammarLesson[]=[...b2TenseNarration,...b2ConditionModal,...b2Subjunctive,...b2VerbalForms,...b2Pronouns,...b2RelativesPrepositions,...b2Transformations,...b2ReportedSpeech,...b2LogicalRelations,...b2NegationDetermination,...b2Argumentation,...b2CohesionRegister];
export const c1Lessons:GrammarLesson[]=[...c1TemporalViewpoint,...c1LiteraryForms,...c1Counterfactual,...c1MoodSelection,...c1EpistemicModality,...c1NonfiniteForms,...c1DetachedConstructions,...c1ComplexSubordination,...c1ReferenceSystem,...c1DeterminationAgreement,...c1FocusWordOrder,...c1PolyphonyReported,...c1ArgumentLogic,...c1TextCohesion,...c1WordFormationCollocation,...c1RegisterEditing];
