export type GrammarExample = { fr:string; ar:string; parts:{text:string;role:"subject"|"verb"|"object"|"marker"|"adjective"}[] };
export type GrammarLesson = { id:string;number:number;titleFr:string;titleAr:string;category:string;summary:string;rule:string;formula:string;examples:GrammarExample[];correct:string;incorrect:string;note:string };

export const a1Lessons:GrammarLesson[]=[
 {id:"sentence",number:1,titleFr:"La phrase simple",titleAr:"الجملة الفرنسية البسيطة",category:"الجملة",summary:"ترتيب العناصر الأساسية في الجملة المثبتة.",rule:"يأتي الفاعل عادةً أولًا، ثم الفعل المصرف، ثم المفعول أو المعلومة المكملة. يجب أن يتطابق الفعل مع الفاعل.",formula:"Sujet + Verbe + Complément",examples:[
  {fr:"Je parle français.",ar:"أنا أتحدث الفرنسية.",parts:[{text:"Je",role:"subject"},{text:"parle",role:"verb"},{text:"français",role:"object"}]},
  {fr:"Nadia habite à Paris.",ar:"نادية تسكن في باريس.",parts:[{text:"Nadia",role:"subject"},{text:"habite",role:"verb"},{text:"à Paris",role:"object"}]}],correct:"Nous étudions la grammaire.",incorrect:"Nous la grammaire étudions.",note:"يمكن تقديم بعض المكملات للتأكيد، لكن ترتيب S + V + C هو الأساس الأنسب للمبتدئ."},
 {id:"subject-pronouns",number:2,titleFr:"Les pronoms sujets",titleAr:"ضمائر الفاعل",category:"الضمائر",summary:"اختيار الضمير الذي يحدد تصريف الفعل.",rule:"ضمائر الفاعل هي: je, tu, il, elle, on, nous, vous, ils, elles. يُستعمل vous للجمع وللاحترام مع شخص واحد.",formula:"Pronom sujet + Verbe conjugué",examples:[
  {fr:"Elle travaille aujourd’hui.",ar:"هي تعمل اليوم.",parts:[{text:"Elle",role:"subject"},{text:"travaille",role:"verb"},{text:"aujourd’hui",role:"object"}]},
  {fr:"Vous parlez lentement.",ar:"أنتم/أنت باحترام تتحدثون ببطء.",parts:[{text:"Vous",role:"subject"},{text:"parlez",role:"verb"},{text:"lentement",role:"object"}]}],correct:"Ils arrivent à huit heures.",incorrect:"Ils arrive à huit heures.",note:"on يُصرف مثل il وelle، ويستعمل كثيرًا بمعنى «نحن» في الحديث اليومي."},
 {id:"articles",number:3,titleFr:"Les articles",titleAr:"أدوات التعريف والتنكير",category:"الأسماء",summary:"التمييز بين le, la, l’, les و un, une, des.",rule:"تُستعمل أدوات التعريف مع الشيء المعروف أو العام، وأدوات التنكير مع شيء غير محدد. تتحول le وla إلى l’ قبل صوت متحرك أو h صامت.",formula:"le / la / l’ / les — un / une / des",examples:[
  {fr:"J’ouvre la fenêtre.",ar:"أنا أفتح النافذة المعروفة.",parts:[{text:"J’",role:"subject"},{text:"ouvre",role:"verb"},{text:"la",role:"marker"},{text:"fenêtre",role:"object"}]},
  {fr:"Il achète un livre.",ar:"هو يشتري كتابًا غير محدد.",parts:[{text:"Il",role:"subject"},{text:"achète",role:"verb"},{text:"un",role:"marker"},{text:"livre",role:"object"}]}],correct:"L’école est ouverte.",incorrect:"La école est ouverte.",note:"جنس الأداة يتبع جنس الاسم، وليس جنس الشخص الذي يتكلم."},
 {id:"gender-number",number:4,titleFr:"Le genre et le nombre",titleAr:"المذكر والمؤنث والمفرد والجمع",category:"الأسماء",summary:"فهم جنس الاسم وبناء الجمع المنتظم.",rule:"لكل اسم فرنسي جنس نحوي يجب حفظه مع أداته. غالبًا يضاف s لبناء الجمع، ولا يُنطق هذا الحرف في معظم الكلمات.",formula:"un étudiant → une étudiante · le livre → les livres",examples:[
  {fr:"Une étudiante française arrive.",ar:"تصل طالبة فرنسية.",parts:[{text:"Une",role:"marker"},{text:"étudiante",role:"subject"},{text:"française",role:"adjective"},{text:"arrive",role:"verb"}]},
  {fr:"Les voitures sont rouges.",ar:"السيارات حمراء.",parts:[{text:"Les voitures",role:"subject"},{text:"sont",role:"verb"},{text:"rouges",role:"adjective"}]}],correct:"Des maisons blanches.",incorrect:"Des maison blanche.",note:"توجد جموع غير منتظمة مثل cheval → chevaux؛ تُدرَس لاحقًا ضمن درس خاص."},
 {id:"etre-avoir",number:5,titleFr:"Être et avoir au présent",titleAr:"الفعلان être و avoir في الحاضر",category:"الأفعال",summary:"أكثر فعلين استعمالًا في الفرنسية.",rule:"être يصف الهوية أو الحالة، وavoir يدل على الملكية ويدخل في تعبيرات مثل العمر والجوع والعطش.",formula:"être: suis, es, est, sommes, êtes, sont · avoir: ai, as, a, avons, avez, ont",examples:[
  {fr:"Nous sommes prêts.",ar:"نحن مستعدون.",parts:[{text:"Nous",role:"subject"},{text:"sommes",role:"verb"},{text:"prêts",role:"adjective"}]},
  {fr:"J’ai vingt ans.",ar:"عمري عشرون سنة.",parts:[{text:"J’",role:"subject"},{text:"ai",role:"verb"},{text:"vingt ans",role:"object"}]}],correct:"Elle a faim.",incorrect:"Elle est faim.",note:"يُعبّر عن العمر بالفرنسية باستعمال avoir، وليس être."},
 {id:"present-er",number:6,titleFr:"Le présent des verbes en -er",titleAr:"حاضر أفعال المجموعة الأولى",category:"الأفعال",summary:"تصريف الأفعال المنتظمة المنتهية بـ -er.",rule:"نحذف -er من المصدر ثم نضيف النهايات: -e, -es, -e, -ons, -ez, -ent. غالبًا لا تُنطق -ent في آخر صيغة ils/elles.",formula:"parler → parle, parles, parle, parlons, parlez, parlent",examples:[
  {fr:"Tu regardes le film.",ar:"أنت تشاهد الفيلم.",parts:[{text:"Tu",role:"subject"},{text:"regardes",role:"verb"},{text:"le film",role:"object"}]},
  {fr:"Nous habitons à Riyad.",ar:"نحن نسكن في الرياض.",parts:[{text:"Nous",role:"subject"},{text:"habitons",role:"verb"},{text:"à Riyad",role:"object"}]}],correct:"Elles parlent français.",incorrect:"Elles parler français.",note:"الفعل aller ينتهي بـ -er لكنه غير منتظم ولا يتبع هذا النموذج."},
 {id:"adjectives",number:7,titleFr:"L’accord de l’adjectif",titleAr:"مطابقة الصفة",category:"الصفات",summary:"مطابقة الصفة للاسم في الجنس والعدد.",rule:"تتطابق الصفة مع الاسم الذي تصفه. يضاف غالبًا e للمؤنث وs للجمع، لكن بعض الصفات لها أشكال خاصة.",formula:"masculin: petit · féminin: petite · pluriel: petits / petites",examples:[
  {fr:"C’est une petite ville.",ar:"إنها مدينة صغيرة.",parts:[{text:"C’",role:"subject"},{text:"est",role:"verb"},{text:"une",role:"marker"},{text:"petite",role:"adjective"},{text:"ville",role:"object"}]},
  {fr:"Les exercices sont faciles.",ar:"التمارين سهلة.",parts:[{text:"Les exercices",role:"subject"},{text:"sont",role:"verb"},{text:"faciles",role:"adjective"}]}],correct:"Une voiture française.",incorrect:"Une voiture français.",note:"كثير من الصفات يأتي بعد الاسم، بينما صفات شائعة مثل petit وgrand وbeau تأتي غالبًا قبله."},
 {id:"negation",number:8,titleFr:"La négation ne… pas",titleAr:"النفي بـ ne… pas",category:"الجملة",summary:"تحويل الجملة المثبتة إلى منفية.",rule:"نضع ne قبل الفعل المصرف وpas بعده. تتحول ne إلى n’ قبل صوت متحرك أو h صامت. في الكتابة المعيارية لا نحذف ne.",formula:"Sujet + ne / n’ + Verbe + pas + Complément",examples:[
  {fr:"Je ne comprends pas la question.",ar:"أنا لا أفهم السؤال.",parts:[{text:"Je",role:"subject"},{text:"ne",role:"marker"},{text:"comprends",role:"verb"},{text:"pas",role:"marker"},{text:"la question",role:"object"}]},
  {fr:"Elle n’habite pas ici.",ar:"هي لا تسكن هنا.",parts:[{text:"Elle",role:"subject"},{text:"n’",role:"marker"},{text:"habite",role:"verb"},{text:"pas",role:"marker"},{text:"ici",role:"object"}]}],correct:"Nous ne parlons pas vite.",incorrect:"Nous parlons ne pas vite.",note:"قد تُحذف ne في الكلام اليومي غير الرسمي، لكنها تبقى مطلوبة في الفرنسية المعيارية."},
 {id:"questions",number:9,titleFr:"Poser une question",titleAr:"تكوين السؤال",category:"الجملة",summary:"ثلاث طرق أساسية للسؤال.",rule:"يمكن السؤال بنبرة مرتفعة، أو باستعمال est-ce que، أو بقلب الفاعل والفعل في الأسلوب الرسمي. للمبتدئ تعد est-ce que واضحة وآمنة.",formula:"Est-ce que + Sujet + Verbe + Complément ?",examples:[
  {fr:"Est-ce que vous parlez français ?",ar:"هل تتحدثون الفرنسية؟",parts:[{text:"Est-ce que",role:"marker"},{text:"vous",role:"subject"},{text:"parlez",role:"verb"},{text:"français",role:"object"}]},
  {fr:"Où habites-tu ?",ar:"أين تسكن؟",parts:[{text:"Où",role:"marker"},{text:"habites",role:"verb"},{text:"-tu",role:"subject"}]}],correct:"Tu travailles aujourd’hui ?",incorrect:"Est-ce que travailles-tu aujourd’hui ?",note:"لا نجمع عادةً بين est-ce que وقلب الفاعل في السؤال نفسه."},
 {id:"possessives",number:10,titleFr:"Les déterminants possessifs",titleAr:"صفات الملكية",category:"المحددات",summary:"التعبير عن الملكية مع الاسم.",rule:"تتطابق صفة الملكية مع الشيء المملوك لا مع المالك: mon/ma/mes، ton/ta/tes، son/sa/ses، notre/nos، votre/vos، leur/leurs.",formula:"possessif + nom",examples:[
  {fr:"Voici ma voiture.",ar:"هذه سيارتي.",parts:[{text:"Voici",role:"verb"},{text:"ma",role:"marker"},{text:"voiture",role:"object"}]},
  {fr:"Ils cherchent leurs clés.",ar:"هم يبحثون عن مفاتيحهم.",parts:[{text:"Ils",role:"subject"},{text:"cherchent",role:"verb"},{text:"leurs",role:"marker"},{text:"clés",role:"object"}]}],correct:"Elle aime son travail.",incorrect:"Elle aime sa travail.",note:"نقول mon amie لا ma amie لتجنب التقاء صوتين متحركين، مع بقاء amie مؤنثًا."},
 {id:"place-prepositions",number:11,titleFr:"Les prépositions de lieu",titleAr:"حروف الجر للمكان والبلدان",category:"حروف الجر",summary:"اختيار à، en، au و aux.",rule:"نستعمل à مع المدن، en مع غالبية البلدان المؤنثة أو التي تبدأ بصوت متحرك، au مع البلدان المذكرة، وaux مع البلدان بصيغة الجمع.",formula:"à Paris · en France · au Canada · aux États-Unis",examples:[
  {fr:"J’habite à Djeddah.",ar:"أسكن في جدة.",parts:[{text:"J’",role:"subject"},{text:"habite",role:"verb"},{text:"à",role:"marker"},{text:"Djeddah",role:"object"}]},
  {fr:"Nous voyageons en France.",ar:"نسافر إلى فرنسا.",parts:[{text:"Nous",role:"subject"},{text:"voyageons",role:"verb"},{text:"en",role:"marker"},{text:"France",role:"object"}]}],correct:"Il travaille au Japon.",incorrect:"Il travaille à le Japon.",note:"au هو دمج à + le، وaux هو دمج à + les."},
 {id:"presentatives",number:12,titleFr:"C’est, ce sont et il y a",titleAr:"التقديم والوصف ووجود الأشياء",category:"الجملة",summary:"تقديم شخص أو شيء والتعبير عن وجوده.",rule:"نستعمل c’est قبل المفرد لتقديمه، وce sont قبل الجمع في الاستعمال المعياري، وil y a للتعبير عن وجود شيء أو أشخاص.",formula:"C’est + singulier · Ce sont + pluriel · Il y a + nom",examples:[
  {fr:"C’est mon professeur.",ar:"هذا أستاذي.",parts:[{text:"C’",role:"subject"},{text:"est",role:"verb"},{text:"mon professeur",role:"object"}]},
  {fr:"Il y a deux cafés ici.",ar:"يوجد مقهيان هنا.",parts:[{text:"Il y a",role:"verb"},{text:"deux cafés",role:"object"},{text:"ici",role:"marker"}]}],correct:"Ce sont mes amis.",incorrect:"C’est mes amis.",note:"يشيع c’est أمام الجمع في الكلام، لكن ce sont هو النموذج المعياري الذي يتعلمه الدارس أولًا."}
];
