// A fixed, reviewed snapshot: no external country or flag request is made at runtime.
// Source and license notes: country-data-source.md.
export type CountryFlagEntry={code:string;fr:string;ar:string;stay:string;origin:string};

export const A1_COUNTRY_FLAGS:CountryFlagEntry[]=[
 {code:"AF",fr:"Afghanistan",ar:"أفغانستان",stay:"en",origin:"d’"},
 {code:"ZA",fr:"Afrique du Sud",ar:"جنوب أفريقيا",stay:"en",origin:"d’"},
 {code:"AL",fr:"Albanie",ar:"ألبانيا",stay:"en",origin:"d’"},
 {code:"DZ",fr:"Algérie",ar:"الجزائر",stay:"en",origin:"d’"},
 {code:"DE",fr:"Allemagne",ar:"ألمانيا",stay:"en",origin:"d’"},
 {code:"AD",fr:"Andorre",ar:"أندورا",stay:"en",origin:"d’"},
 {code:"AO",fr:"Angola",ar:"أنغولا",stay:"en",origin:"d’"},
 {code:"AG",fr:"Antigua-et-Barbuda",ar:"أنتيغوا وباربودا",stay:"à",origin:"d’"},
 {code:"SA",fr:"Arabie saoudite",ar:"السعودية",stay:"en",origin:"d’"},
 {code:"AR",fr:"Argentine",ar:"الأرجنتين",stay:"en",origin:"d’"},
 {code:"AM",fr:"Arménie",ar:"أرمينيا",stay:"en",origin:"d’"},
 {code:"AU",fr:"Australie",ar:"أستراليا",stay:"en",origin:"d’"},
 {code:"AT",fr:"Autriche",ar:"النمسا",stay:"en",origin:"d’"},
 {code:"AZ",fr:"Azerbaïdjan",ar:"أذربيجان",stay:"en",origin:"d’"},
 {code:"BS",fr:"Bahamas",ar:"البهاما",stay:"aux",origin:"des"},
 {code:"BH",fr:"Bahreïn",ar:"البحرين",stay:"à",origin:"de"},
 {code:"BD",fr:"Bangladesh",ar:"بنغلاديش",stay:"au",origin:"du"},
 {code:"BB",fr:"Barbade",ar:"باربادوس",stay:"à la",origin:"de la"},
 {code:"BY",fr:"Bélarus",ar:"بيلاروسيا",stay:"au",origin:"du"},
 {code:"BE",fr:"Belgique",ar:"بلجيكا",stay:"en",origin:"de"},
 {code:"BZ",fr:"Bélize",ar:"بليز",stay:"au",origin:"du"},
 {code:"BJ",fr:"Bénin",ar:"بنين",stay:"au",origin:"du"},
 {code:"BT",fr:"Bhoutan",ar:"بوتان",stay:"au",origin:"du"},
 {code:"MM",fr:"Birmanie",ar:"ميانمار",stay:"en",origin:"de"},
 {code:"BO",fr:"Bolivie",ar:"بوليفيا",stay:"en",origin:"de"},
 {code:"BA",fr:"Bosnie-Herzégovine",ar:"البوسنة والهرسك",stay:"en",origin:"de"},
 {code:"BW",fr:"Botswana",ar:"بوتسوانا",stay:"au",origin:"du"},
 {code:"BR",fr:"Brésil",ar:"البرازيل",stay:"au",origin:"du"},
 {code:"BN",fr:"Brunéi Darussalam",ar:"بروناي",stay:"à",origin:"de"},
 {code:"BG",fr:"Bulgarie",ar:"بلغاريا",stay:"en",origin:"de"},
 {code:"BF",fr:"Burkina Faso",ar:"بوركينا فاسو",stay:"au",origin:"du"},
 {code:"BI",fr:"Burundi",ar:"بوروندي",stay:"au",origin:"du"},
 {code:"KH",fr:"Cambodge",ar:"كمبوديا",stay:"au",origin:"du"},
 {code:"CM",fr:"Cameroun",ar:"الكاميرون",stay:"au",origin:"du"},
 {code:"CA",fr:"Canada",ar:"كندا",stay:"au",origin:"du"},
 {code:"CV",fr:"Cap-Vert",ar:"كابو فيردي",stay:"au",origin:"du"},
 {code:"CL",fr:"Chili",ar:"تشيلي",stay:"au",origin:"du"},
 {code:"CN",fr:"Chine",ar:"الصين",stay:"en",origin:"de"},
 {code:"CY",fr:"Chypre",ar:"قبرص",stay:"à",origin:"de"},
 {code:"CO",fr:"Colombie",ar:"كولومبيا",stay:"en",origin:"de"},
 {code:"KM",fr:"Comores",ar:"جزر القمر",stay:"aux",origin:"des"},
 {code:"CG",fr:"Congo",ar:"جمهورية الكونغو",stay:"au",origin:"du"},
 {code:"KP",fr:"Corée du Nord",ar:"كوريا الشمالية",stay:"en",origin:"de"},
 {code:"KR",fr:"Corée du Sud",ar:"كوريا الجنوبية",stay:"en",origin:"de"},
 {code:"CR",fr:"Costa Rica",ar:"كوستاريكا",stay:"au",origin:"du"},
 {code:"CI",fr:"Côte d’Ivoire",ar:"ساحل العاج",stay:"en",origin:"de"},
 {code:"HR",fr:"Croatie",ar:"كرواتيا",stay:"en",origin:"de"},
 {code:"CU",fr:"Cuba",ar:"كوبا",stay:"à",origin:"de"},
 {code:"DK",fr:"Danemark",ar:"الدنمارك",stay:"au",origin:"du"},
 {code:"DJ",fr:"Djibouti",ar:"جيبوتي",stay:"à",origin:"de"},
 {code:"DM",fr:"Dominique",ar:"دومينيكا",stay:"à la",origin:"de la"},
 {code:"EG",fr:"Égypte",ar:"مصر",stay:"en",origin:"d’"},
 {code:"AE",fr:"Émirats arabes unis",ar:"الإمارات",stay:"aux",origin:"des"},
 {code:"EC",fr:"Équateur",ar:"الإكوادور",stay:"en",origin:"d’"},
 {code:"ER",fr:"Érythrée",ar:"إريتريا",stay:"en",origin:"d’"},
 {code:"ES",fr:"Espagne",ar:"إسبانيا",stay:"en",origin:"d’"},
 {code:"EE",fr:"Estonie",ar:"إستونيا",stay:"en",origin:"d’"},
 {code:"SZ",fr:"Eswatini",ar:"إسواتيني",stay:"en",origin:"d’"},
 {code:"US",fr:"États-Unis",ar:"الولايات المتحدة",stay:"aux",origin:"des"},
 {code:"ET",fr:"Éthiopie",ar:"إثيوبيا",stay:"en",origin:"d’"},
 {code:"FJ",fr:"Fidji",ar:"فيجي",stay:"aux",origin:"des"},
 {code:"FI",fr:"Finlande",ar:"فنلندا",stay:"en",origin:"de"},
 {code:"FR",fr:"France",ar:"فرنسا",stay:"en",origin:"de"},
 {code:"GA",fr:"Gabon",ar:"الغابون",stay:"au",origin:"du"},
 {code:"GM",fr:"Gambie",ar:"غامبيا",stay:"en",origin:"de"},
 {code:"GE",fr:"Géorgie",ar:"جورجيا",stay:"en",origin:"de"},
 {code:"GH",fr:"Ghana",ar:"غانا",stay:"au",origin:"du"},
 {code:"GR",fr:"Grèce",ar:"اليونان",stay:"en",origin:"de"},
 {code:"GD",fr:"Grenade",ar:"غرينادا",stay:"à la",origin:"de la"},
 {code:"GT",fr:"Guatemala",ar:"غواتيمالا",stay:"au",origin:"du"},
 {code:"GN",fr:"Guinée",ar:"غينيا",stay:"en",origin:"de"},
 {code:"GQ",fr:"Guinée équatoriale",ar:"غينيا الاستوائية",stay:"en",origin:"de"},
 {code:"GW",fr:"Guinée-Bissau",ar:"غينيا بيساو",stay:"en",origin:"de"},
 {code:"GY",fr:"Guyana",ar:"غيانا",stay:"au",origin:"du"},
 {code:"HT",fr:"Haïti",ar:"هايتي",stay:"à",origin:"d’"},
 {code:"HN",fr:"Honduras",ar:"هندوراس",stay:"au",origin:"du"},
 {code:"HU",fr:"Hongrie",ar:"المجر",stay:"en",origin:"de"},
 {code:"MU",fr:"Île Maurice",ar:"موريشيوس",stay:"à l’",origin:"de l’"},
 {code:"MH",fr:"Îles Marshall",ar:"جزر مارشال",stay:"aux",origin:"des"},
 {code:"SB",fr:"Îles Salomon",ar:"جزر سليمان",stay:"aux",origin:"des"},
 {code:"IN",fr:"Inde",ar:"الهند",stay:"en",origin:"d’"},
 {code:"ID",fr:"Indonésie",ar:"إندونيسيا",stay:"en",origin:"d’"},
 {code:"IQ",fr:"Irak",ar:"العراق",stay:"en",origin:"d’"},
 {code:"IR",fr:"Iran",ar:"إيران",stay:"en",origin:"d’"},
 {code:"IE",fr:"Irlande",ar:"أيرلندا",stay:"en",origin:"d’"},
 {code:"IS",fr:"Islande",ar:"آيسلندا",stay:"en",origin:"d’"},
 {code:"IT",fr:"Italie",ar:"إيطاليا",stay:"en",origin:"d’"},
 {code:"JM",fr:"Jamaïque",ar:"جامايكا",stay:"à la",origin:"de la"},
 {code:"JP",fr:"Japon",ar:"اليابان",stay:"au",origin:"du"},
 {code:"JO",fr:"Jordanie",ar:"الأردن",stay:"en",origin:"de"},
 {code:"KZ",fr:"Kazakhstan",ar:"كازاخستان",stay:"au",origin:"du"},
 {code:"KE",fr:"Kenya",ar:"كينيا",stay:"au",origin:"du"},
 {code:"KG",fr:"Kirghizistan",ar:"قيرغيزستان",stay:"au",origin:"du"},
 {code:"KI",fr:"Kiribati",ar:"كيريباتي",stay:"à",origin:"de"},
 {code:"XK",fr:"Kosovo",ar:"كوسوفو",stay:"au",origin:"du"},
 {code:"KW",fr:"Koweït",ar:"الكويت",stay:"au",origin:"du"},
 {code:"LA",fr:"Laos",ar:"لاوس",stay:"au",origin:"du"},
 {code:"LS",fr:"Lesotho",ar:"ليسوتو",stay:"au",origin:"du"},
 {code:"LV",fr:"Lettonie",ar:"لاتفيا",stay:"en",origin:"de"},
 {code:"LB",fr:"Liban",ar:"لبنان",stay:"au",origin:"du"},
 {code:"LR",fr:"Libéria",ar:"ليبيريا",stay:"au",origin:"du"},
 {code:"LY",fr:"Libye",ar:"ليبيا",stay:"en",origin:"de"},
 {code:"LI",fr:"Liechtenstein",ar:"ليختنشتاين",stay:"au",origin:"du"},
 {code:"LT",fr:"Lituanie",ar:"ليتوانيا",stay:"en",origin:"de"},
 {code:"LU",fr:"Luxembourg",ar:"لوكسمبورغ",stay:"au",origin:"du"},
 {code:"MK",fr:"Macédoine du Nord",ar:"شمال مقدونيا",stay:"en",origin:"de"},
 {code:"MG",fr:"Madagascar",ar:"مدغشقر",stay:"à",origin:"de"},
 {code:"MY",fr:"Malaisie",ar:"ماليزيا",stay:"en",origin:"de"},
 {code:"MW",fr:"Malawi",ar:"مالاوي",stay:"au",origin:"du"},
 {code:"MV",fr:"Maldives",ar:"المالديف",stay:"aux",origin:"des"},
 {code:"ML",fr:"Mali",ar:"مالي",stay:"au",origin:"du"},
 {code:"MT",fr:"Malte",ar:"مالطا",stay:"à",origin:"de"},
 {code:"MA",fr:"Maroc",ar:"المغرب",stay:"au",origin:"du"},
 {code:"MR",fr:"Mauritanie",ar:"موريتانيا",stay:"en",origin:"de"},
 {code:"MX",fr:"Mexique",ar:"المكسيك",stay:"au",origin:"du"},
 {code:"FM",fr:"Micronésie",ar:"ميكرونيسيا",stay:"en",origin:"de"},
 {code:"MD",fr:"Moldavie",ar:"مولدوفا",stay:"en",origin:"de"},
 {code:"MC",fr:"Monaco",ar:"موناكو",stay:"à",origin:"de"},
 {code:"MN",fr:"Mongolie",ar:"منغوليا",stay:"en",origin:"de"},
 {code:"ME",fr:"Monténégro",ar:"الجبل الأسود",stay:"au",origin:"du"},
 {code:"MZ",fr:"Mozambique",ar:"موزمبيق",stay:"au",origin:"du"},
 {code:"NA",fr:"Namibie",ar:"ناميبيا",stay:"en",origin:"de"},
 {code:"NR",fr:"Nauru",ar:"ناورو",stay:"à",origin:"de"},
 {code:"NP",fr:"Népal",ar:"نيبال",stay:"au",origin:"du"},
 {code:"NI",fr:"Nicaragua",ar:"نيكاراغوا",stay:"au",origin:"du"},
 {code:"NE",fr:"Niger",ar:"النيجر",stay:"au",origin:"du"},
 {code:"NG",fr:"Nigéria",ar:"نيجيريا",stay:"au",origin:"du"},
 {code:"NO",fr:"Norvège",ar:"النرويج",stay:"en",origin:"de"},
 {code:"NZ",fr:"Nouvelle-Zélande",ar:"نيوزيلندا",stay:"en",origin:"de"},
 {code:"OM",fr:"Oman",ar:"عمان",stay:"à",origin:"d’"},
 {code:"UG",fr:"Ouganda",ar:"أوغندا",stay:"en",origin:"d’"},
 {code:"UZ",fr:"Ouzbékistan",ar:"أوزباكستان",stay:"en",origin:"d’"},
 {code:"PK",fr:"Pakistan",ar:"باكستان",stay:"au",origin:"du"},
 {code:"PW",fr:"Palaos",ar:"بالاو",stay:"aux",origin:"des"},
 {code:"PS",fr:"Palestine",ar:"فلسطين",stay:"en",origin:"de"},
 {code:"PA",fr:"Panamá",ar:"بنما",stay:"au",origin:"du"},
 {code:"PG",fr:"Papouasie-Nouvelle-Guinée",ar:"بابوا غينيا الجديدة",stay:"en",origin:"de"},
 {code:"PY",fr:"Paraguay",ar:"باراغواي",stay:"au",origin:"du"},
 {code:"NL",fr:"Pays-Bas",ar:"هولندا",stay:"aux",origin:"des"},
 {code:"PE",fr:"Pérou",ar:"بيرو",stay:"au",origin:"du"},
 {code:"PH",fr:"Philippines",ar:"الفلبين",stay:"aux",origin:"des"},
 {code:"PL",fr:"Pologne",ar:"بولندا",stay:"en",origin:"de"},
 {code:"PT",fr:"Portugal",ar:"البرتغال",stay:"au",origin:"du"},
 {code:"QA",fr:"Qatar",ar:"قطر",stay:"au",origin:"du"},
 {code:"CF",fr:"République centrafricaine",ar:"جمهورية أفريقيا الوسطى",stay:"en",origin:"de la"},
 {code:"CD",fr:"République démocratique du Congo",ar:"جمهورية الكونغو الديمقراطية",stay:"en",origin:"de la"},
 {code:"DO",fr:"République dominicaine",ar:"جمهورية الدومينيكان",stay:"en",origin:"de la"},
 {code:"RO",fr:"Roumanie",ar:"رومانيا",stay:"en",origin:"de"},
 {code:"GB",fr:"Royaume-Uni",ar:"المملكة المتحدة",stay:"au",origin:"du"},
 {code:"RU",fr:"Russie",ar:"روسيا",stay:"en",origin:"de"},
 {code:"RW",fr:"Rwanda",ar:"رواندا",stay:"au",origin:"du"},
 {code:"KN",fr:"Saint-Christophe-et-Niévès",ar:"سانت كيتس ونيفيس",stay:"à",origin:"de"},
 {code:"SM",fr:"Saint-Marin",ar:"سان مارينو",stay:"à",origin:"de"},
 {code:"VC",fr:"Saint-Vincent-et-les Grenadines",ar:"سانت فينسنت والغرينادين",stay:"à",origin:"de"},
 {code:"LC",fr:"Sainte-Lucie",ar:"سانت لوسيا",stay:"à",origin:"de"},
 {code:"SV",fr:"Salvador",ar:"السلفادور",stay:"au",origin:"du"},
 {code:"WS",fr:"Samoa",ar:"ساموا",stay:"au",origin:"du"},
 {code:"ST",fr:"Sao Tomé-et-Principe",ar:"ساو تومي وبرينسيب",stay:"à",origin:"de"},
 {code:"SN",fr:"Sénégal",ar:"السنغال",stay:"au",origin:"du"},
 {code:"RS",fr:"Serbie",ar:"صربيا",stay:"en",origin:"de"},
 {code:"SC",fr:"Seychelles",ar:"سيشل",stay:"aux",origin:"des"},
 {code:"SL",fr:"Sierra Leone",ar:"سيراليون",stay:"en",origin:"de"},
 {code:"SG",fr:"Singapour",ar:"سنغافورة",stay:"à",origin:"de"},
 {code:"SK",fr:"Slovaquie",ar:"سلوفاكيا",stay:"en",origin:"de"},
 {code:"SI",fr:"Slovénie",ar:"سلوفينيا",stay:"en",origin:"de"},
 {code:"SO",fr:"Somalie",ar:"الصومال",stay:"en",origin:"de"},
 {code:"SD",fr:"Soudan",ar:"السودان",stay:"au",origin:"du"},
 {code:"SS",fr:"Soudan du Sud",ar:"جنوب السودان",stay:"au",origin:"du"},
 {code:"LK",fr:"Sri Lanka",ar:"سريلانكا",stay:"au",origin:"du"},
 {code:"SE",fr:"Suède",ar:"السويد",stay:"en",origin:"de"},
 {code:"CH",fr:"Suisse",ar:"سويسرا",stay:"en",origin:"de"},
 {code:"SR",fr:"Suriname",ar:"سورينام",stay:"au",origin:"du"},
 {code:"SY",fr:"Syrie",ar:"سوريا",stay:"en",origin:"de"},
 {code:"TJ",fr:"Tadjikistan",ar:"طاجيكستان",stay:"au",origin:"du"},
 {code:"TW",fr:"Taïwan",ar:"تايوان",stay:"à",origin:"de"},
 {code:"TZ",fr:"Tanzanie",ar:"تنزانيا",stay:"en",origin:"de"},
 {code:"TD",fr:"Tchad",ar:"تشاد",stay:"au",origin:"du"},
 {code:"CZ",fr:"Tchéquie",ar:"التشيك",stay:"en",origin:"de"},
 {code:"TH",fr:"Thaïlande",ar:"تايلند",stay:"en",origin:"de"},
 {code:"TL",fr:"Timor-Oriental",ar:"تيمور الشرقية",stay:"au",origin:"du"},
 {code:"TG",fr:"Togo",ar:"توغو",stay:"au",origin:"du"},
 {code:"TO",fr:"Tonga",ar:"تونغا",stay:"aux",origin:"des"},
 {code:"TT",fr:"Trinité-et-Tobago",ar:"ترينيداد وتوباغو",stay:"à",origin:"de"},
 {code:"TN",fr:"Tunisie",ar:"تونس",stay:"en",origin:"de"},
 {code:"TM",fr:"Turkménistan",ar:"تركمانستان",stay:"au",origin:"du"},
 {code:"TR",fr:"Turquie",ar:"تركيا",stay:"en",origin:"de"},
 {code:"TV",fr:"Tuvalu",ar:"توفالو",stay:"à",origin:"de"},
 {code:"UA",fr:"Ukraine",ar:"أوكرانيا",stay:"en",origin:"d’"},
 {code:"UY",fr:"Uruguay",ar:"الأوروغواي",stay:"en",origin:"d’"},
 {code:"VU",fr:"Vanuatu",ar:"فانواتو",stay:"à",origin:"de"},
 {code:"VA",fr:"Vatican",ar:"الفاتيكان",stay:"au",origin:"du"},
 {code:"VE",fr:"Venezuela",ar:"فنزويلا",stay:"au",origin:"du"},
 {code:"VN",fr:"Vietnam",ar:"فيتنام",stay:"au",origin:"du"},
 {code:"YE",fr:"Yémen",ar:"اليمن",stay:"au",origin:"du"},
 {code:"ZM",fr:"Zambie",ar:"زامبيا",stay:"en",origin:"de"},
 {code:"ZW",fr:"Zimbabwe",ar:"زيمبابوي",stay:"au",origin:"du"},
];

export function countryStaySentence(country:CountryFlagEntry){
 return `J’habite ${country.stay}${country.stay.endsWith("’")?"":" "}${country.fr}.`;
}

export function countryOriginSentence(country:CountryFlagEntry){
 return `Je viens ${country.origin}${country.origin.endsWith("’")?"":" "}${country.fr}.`;
}
